### ISSUE TITLE
Short intros to scripts

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#10]
Hi!

http://aksharamukha.appspot.com/#/rosetta-stone is fascinating! It would've been nice to include a two line intro (shown as the third column in the table, or as a tooltip) for each script. As it is, I needed to look at the wikipedia quite a bit.

**Comment by virtualvinodh** [comment]
Would it be OK if I can pull a two or three line intro from Wikipedia/Script Source only as a tooltip?  Having a third column might crowd the page. 

Ideally, I want to overlay them on a map along with a slider for time. But we'll see, the tooltip is a good start :)

**Comment by virtualvinodh** [comment]
𑀢𑀣𑀸 𑀓𑀭𑀺𑀱𑁆𑀬𑀸𑀫𑀺 :)

**Comment by virtualvinodh** [comment]
It's been done.

In fact, even the script description pages have a short intro now. Both the script matrix and the rosetta stone pages have been linked back to the description pages.

Do let me know if it looks OK.

**Comment by vvasuki** [comment]
𑀲𑀫𑁆𑀬𑀕𑀲𑁆𑀢𑀺 𑀪𑁄𑀂 🙏
