### ISSUE TITLE
Typing Devanagari in Readable Mode to use Aksharmukha as Keyboard

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#102]
Allow one to type in Readable mode instead of other complicated modes such as ITRANS, HK....etc

अ आ इ ई उ ऊ ऋ ॠ ऌ ॡ ए ऐ ओ औ **ऍ ऑ** अः 
a aa i ee u oo ri' ree' li' lee' e ai o au **a o** ah' .....Transliteration 

a  aa i ee u oo ri' ree' li' lee' e ai o au a o ah' ......Typed Input
अ आ इ ई उ ऊ ऋ ॠ ऌ ॡ ए ऐ ओ औ **अ ओ** अः...............Typed output

ऍ, ऑ > a", o" / ae, aw ( suggested new transliteration) or **as suggested by you**.

**Comment by virtualvinodh** [comment]
You can already do that here:

https://aksharamukha.appspot.com/input/Devanagari

**Comment by geethub** [comment]
a aa i ii u uu ru' ruu' lu' luu' e ee e' ee' ai o oo am' am; ah' (Typing Keystrokes)
अ आ इ ई उ ऊ ऋ ॠ ऌ ॡ ऎ ए ऍ एॕ ऐ ऒ ओ अं अँ अः (output)

Since ए, ऍ and ओ   letters are used often in writings you may change typing keystrokes in this order. 
/ e ee e' ee'  /  ऎ ए ऍ एॕ  /  >>> **/ ee e e' ee'  /  ऎ ए ऍ एॕ  /** 
/o oo / ऒ ओ  >>> **/oo  o / ऒ ओ /**

**Comment by the-solipsist** [comment]
Hi @geethub. [This comparison](https://github.com/virtualvinodh/aksharamukha/issues/158) between Aksharaa (input) and Roman Readable (output) might be helpful to you.
