### ISSUE TITLE
Add Guptā Script in Transliteration

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#103]
Date of composition
Haraprasad Shastri and Cecil Bendall, in about 1898, discovered an old palm-leaf manuscript of Skanda Purana in a Kathmandu library in Nepal, written in **Gupta script**.[13][14][15] 
https://en.wikipedia.org/wiki/Skanda_Purana
https://holybooks.com/the-skanda-purana-vol-i-xx/

https://en.wikipedia.org/wiki/Gupta_script
https://omniglot.com/writing/gupta.htm

**Comment by akarshanbiswas** [comment]
Do we have a font? I guess not. Since unicode considers Gupta script to be a stylistic variant of Brahmi script iirc.

**Comment by virtualvinodh** [comment]
There is no font as of now. I don't see any font being developed in the foreseeable future. Please re-open the issue if you have any pointers to a working Unicode font.
