### ISSUE TITLE
Fix text screenshot

### ISSUE THREAD

**Issue by Geochiraltax** [virtualvinodh/aksharamukha#108]
Screenshots aren't rendering properly for _vertically written scripts_ such as Phags-Pa  and Ali Gali.

Here's a sample of the improperly rendered screenshots:

![image](https://user-images.githubusercontent.com/19777432/113397070-188c9a80-93ba-11eb-951e-b55a2d86e33f.png)

![image](https://user-images.githubusercontent.com/19777432/113397120-2b06d400-93ba-11eb-80f8-8f9fe3afe8f9.png)

Here I attach the corresponding screenshots (using built-in windows snipping tool) of actual text, as seen in the converter page:

![image](https://user-images.githubusercontent.com/19777432/113397302-6e614280-93ba-11eb-98a6-1bee9e42bf99.png)

![image](https://user-images.githubusercontent.com/19777432/113397337-7b7e3180-93ba-11eb-967c-f1c2e1edfb72.png)

**Comment by Geochiraltax** [comment]
Adjusted line spacing for readability

**Comment by virtualvinodh** [comment]
I doubt canvas supports vertical orientation fully.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/direction

V

**Comment by virtualvinodh** [comment]
I'm closing this for now.  This is a browser implementation bug. I do hope that at some point canvas will properly support vertical orientiation.
