### ISSUE TITLE
python module

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#11]
Could you please release the backend as a python module which can be installed with pip (like https://github.com/sanskrit-coders/indic_transliteration )

**Comment by virtualvinodh** [comment]
The problem is the documentation. Currently, there is literally no documentation. 

I have to write documentation about each and every option and the code structure. 

I'll see what I can do. But it's gonna be a month or two for this. I will put this in the back burner for now.

**Comment by virtualvinodh** [comment]
done
