### ISSUE TITLE
Support for Shahmukhi consonants in Urdu

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#110]
Gurmukhi-Shahmukhi Mapping can be found here:
https://en.wikipedia.org/wiki/Shahmukhi_alphabet#Consonants

Or this could also be of help:
https://github.com/shabados/gurmukhi-utils/blob/dev/lib/toShahmukhi.js

---

In summary: 
Looks like Shahmukhi atleast has a couple of characters like `لؕ` and `ݨ` which are not in Urdu. 

So in the same Urdu mapping, you could just map `ण` to `ݨ` and `ळ` to `لؕ` and call the script as Urdu-Shahmukhi (because Urdu can be seen as a subset of Shahmukhi)

---

In addition, when _Preserve Source_ is enabled, we can also transliterate `ष` to `ݰ`, `ञ` to `ݩ` and `ङ` to `ݝ`.

**Comment by GokulNC** [comment]
Or in the same Urdu, you could just map `ण` to `ݨ` and `ळ` to `لؕ` and call the script as Urdu-Shahmukhi (because Urdu can be seen as a subset of Shahmukhi)

**Comment by GokulNC** [comment]
This can also be extended for the [Saraiki alphabet](https://en.wikipedia.org/wiki/Saraiki_alphabet#Arabic_script)'s 4 implosive consonants.

ٻ : ॿ
ڄ : ॼ
ݙ : ॾ
ڳ : ॻ

**Comment by virtualvinodh** [comment]
@GokulNC Shahmukhi has been added.

V

**Comment by virtualvinodh** [comment]
> Any reason why Shahmukhi is added separately from Urdu?

It seems to perceived as a separate script even with a separate label. I thought I'll maintain it. Also, in the future if there is an option to transcribe Punjabi this makes it easier in terms of UI. As you know, Punjabi is tonal and the what they write isn't exactly what they pronounce. 

> Also, I did not know about the nasals & liquids aspiration. Even Urdu seems to be having that I guess.

Aah. Then, I can make it common for both Urdu and Shahmukhi.  Thanks for letting me know :)

V
