### ISSUE TITLE
Options to selectively remove apostrophe ருʼம்ʼ → ரும் 

### ISSUE THREAD

**Issue by uberize** [virtualvinodh/aksharamukha#111]
For the conversion amr̥tāṉandaṁ --> அம்ருʼதானந்த³ம்ʼ, there are two apostrophes:

1. One after ரு to indicate that this is the vowel r̥  rather than the consonant+vowel "ru"
2. One after ம் to indicate that this is the anusvara ṁ and not the consonant m

The conversion option "Remove apostrophe" allows you to remove both types of apostrophes above. 

It would be great to be able to specify which type to remove and which one to keep.

**Comment by virtualvinodh** [comment]
@uberize Tamil already has a dozen options :)

I don't know. Is it necessary to add one more?

V
