### ISSUE TITLE
Romanization Schemes

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#118]
Tamil nnna ன coding is defaulting to na ந for n2 and ^na.
Didn't check other coding schemes.
Perhaps defaults to Roman (Readable) scheme?

**Comment by virtualvinodh** [comment]
That shouldn't. 

Could you give me an actual example word or sentence?

V

**Comment by nsesha92** [comment]
I should have taken a screenshot that day, poor notes taking/documenting ..

I think its this:
^nRRi  -->> ந்ருʼ
rest ok.
^nRRI ன்ரூʼ
^nLLi ன்லுʼ
^nLLI ன்லூʼ

Well, I used aksharamukha for a totally different purpose - to code Azhagi+ xml for Tamil Extended and e-Grantamil 7 (and many more) and spotted this error.

**Comment by virtualvinodh** [comment]
Aaah. This is due to the fact that the program tries to be smart and guess where /ந/ is preferred in Sanskrit words (e,g. nrpati).

Please use the preserve source tag and it should not apply any post processing.

V
