### ISSUE TITLE
Language data as (say) json

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#12]
Copying @shreevatsa's suggestion from email -

A suggestion: a lot of domain-specific “data” that goes into a piece of software like this is not specific to the programming language used; 
specifically in this case I'm referring to the script data (such as these) — if these were factored out into say JSON files (and perhaps released as a package of their own) then translating/rewriting the transliteration in another (programming) language would be easier.

**Comment by virtualvinodh** [comment]
https://github.com/virtualvinodh/aksharamukha/blob/master/README.md#json-resource
