### ISSUE TITLE
nnna

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#120]
^nRRi going to ந்ருʼ 
and not to ன்ருʼ

^nRRi ந்ருʼ
^nRRI ன்ரூʼ 
^nLLI ன்லூʼ
^nLLI ன்லூʼ

**Comment by virtualvinodh** [comment]
Hmmm.. I'll have a look.

V

**Comment by virtualvinodh** [comment]
Please use 'Preserver Source' and it should retain the input as such
