### ISSUE TITLE
Numerals 0 to 9 display

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#124]
For Dev and Grantha, there is no option to have numerals in Roman, defaults to Dev १ ... / Tamil ௧. 
For Tamil, there is a Tickable option to choose Tamil numerals: 123 → ௧௨௩
For Tamil Extended, there is no option to choose Tamil numerals, defaults to Roman.
I didn't check other scripts/languages.

Is it possible to have a standard/uniform Tickable option to choose numerals in Roman OR in that language for ALL languages?

**Comment by virtualvinodh** [comment]
@nsesha92 That's actually a good suggestion!

**Comment by yakcz** [comment]
Am I right to conclude this has never been tackled?  At least while converting IAST to Devnag, I do not see an option to preserve roman numerals. 

It would be even better if one could enter some personal mappings too, and that with some wildcard for numbers (e.g. if one wants to convert ||1|| into devanagari, as that is part of the text, while plain 1 which is a result of numbered notes in the editor's pdf should stay in Roman)

**Comment by virtualvinodh** [comment]
There is now a universal option to toggle native numerals (if the orthography prefers roman numerals) or Indo-Arabic numerals (if the orthography prefers roman numerals).

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/4fc094ce-d1b8-48b3-9939-d6a6e11d5c56)

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/ecabc080-6e82-4067-8e87-c868d7ee031c)
