### ISSUE TITLE
Agastya font

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#125]
Agastya font downloaded from Aksharamukha site  "Agastya Sans Extended Tamil font" does not have Latin block.

But the zip file containing both Agastya and Lopamudra downloaded from http://virtualvinodh.com/projects/agastya has Latin block.

Why the difference?

**Comment by virtualvinodh** [comment]
It's just an older version. I should probably update the links.

V

**Comment by virtualvinodh** [comment]
All links should now link to this.

https://github.com/virtualvinodh/agastya-tamil-extended

V
