### ISSUE TITLE
Tamil to Roman transcription: ட followed by another ட series letter - issue 

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#126]
I recently came across a bug when transcribing Tamil to Roman (ISO 15919) or other languages.
காடடை - is getting transcribed as **kāḍaṭai** - instead of **kāḍaḍai** 
Similarly, அடடா - is getting transcribed as **aḍaṭā** - instead of **aḍaḍā** 

However, other combinations such as அடிடா, ஓடிடு, etc. are getting transcribed correctly.

Please check and correct.
Thanks.

**Comment by virtualvinodh** [comment]
Fixed!

V
