### ISSUE TITLE
ISO post-processor for "noLongEO" missing

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#127]
It looks like only `RomanReadableLongEO` is available in python package's PostOptions:
https://github.com/virtualvinodh/aksharamukha/blob/fb5185acc557660849509b3ad04623abf20e5596/aksharamukha-python-package/aksharamukha/PostProcess.py#L638

For ISO Transliteration, when I use `post_options=["noLongEO"]`, I get the following error:
```
AttributeError: module 'aksharamukha.PostProcess' has no attribute 'noLongEO'
```

Kindly check this. Thanks!

**Comment by virtualvinodh** [comment]
I have pushed a new version of the package to pip (v. 1.9).

Also: I have split the Python package to have its own repository.

https://github.com/virtualvinodh/aksharamukha-python

It should work now. The pip package and the site should be in sync now.

Let me know if works. 

V

**Comment by GokulNC** [comment]
Thanks, works now.
