### ISSUE TITLE
Colon (:) gets interpreted as (ः) when seen after a Devanagari word

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#128]
Hindi Input: ([Source](https://hi.wikipedia.org/wiki/%E0%A4%AD%E0%A4%BE%E0%A4%B0%E0%A4%A4))
```
भारत (आधिकारिक नाम: भारत गणराज्य, अंग्रेज़ी: Republic of India)
```

ISO Transliteration:
```
bhārat (ādhikārik nāmaḥ bhārat gaṇarājy, aṅgrejīḥ Republic of India)
```

Please note that the colon mark is interpreted as `ḥ`.

Interestingly, this issue occurs only in Python.
Probably Python's unicode typesystem considers any ":" character immediately after Devanagari characters as implicitly having a ZWJ in between, and hence treating it as ः

**Comment by virtualvinodh** [comment]
That's strange. It shouldn't be happening. I'll have a look!

Thanks for reporting!

**Comment by GokulNC** [comment]
Apologies, false alarm. This issue was because of a [normalizer library](https://github.com/anoopkunchukuttan/indic_nlp_library) that I was using which was replacing colon ':' by visarga if the colon follows a character in the script of interest. So the issue is not from here. :)
