### ISSUE TITLE
Convert websites Issue

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#13]
I did try to read https://www.bbc.com/hindi in IAST mode.
URL conversion works great in straight and Schwa deletion(Hindi) mode but needs improvement in Capitalize sentences mode.
Capitalize sentences mode doesn't capitalize sentences and changes reading format .

**Comment by virtualvinodh** [comment]
This is probably an issue with the Blogspot platform and how it encodes text.
