### ISSUE TITLE
Transliteration of Sanskrit UDHR into 47 scripts

### ISSUE THREAD

**Issue by twardoch** [virtualvinodh/aksharamukha#139]
I used Aksharamukha to convert the Sanskrit translation of the Universal Declaration of Human Rights (the [Devanagari](https://github.com/unicode-org/udhr/blob/master/data/udhr/udhr_san.xml) and [Grantha](https://github.com/unicode-org/udhr/blob/master/data/udhr/udhr_san_gran.xml) versions) into some 47 scripts: 

- [results](https://github.com/twardoch/udhr/tree/master/data/udhr-translit)
- [code](https://github.com/twardoch/udhr/tree/master/translit) — unfortunately it right now uses an unpublished module

Do you think this is something that is workable, sensible? 

I also created a [mapping](https://github.com/twardoch/udhr/blob/master/translit/aksharamukha-scripts.yml) for ISO script and, where needed, language codes for Aksharamukha. This is something that would be useful to have upstream, somehow — a mapping to script and language codes from/to the custom keywords you’re using. 

This is a fantastic project!

**Comment by virtualvinodh** [comment]
That looks great! I had a look at the files and the code, they look reasonable to me.  It should give reasonable results for most of the scripts.  I would be skeptical about some scripts without any living/extinct tradition of writing Sanskrit  whatsoever (like Limbu, Mahajani or Batak). But it should also produce a fairly OK'ish phonetic approximation of the source text. 

The aksharamukha-yaml also looks sensible to me. I would just add one more field, to include the nativize flag. For instance, in Meetei Mayek, setting the flag to false, enables the use of  (archaic) Sanskrit consonants not used in modern Meetei Mayek. Same with Limbu, where it enables the use of (archaic) Anusvara. I may have to individually go through the yaml to verify but I had a quick look and it looks alright. I'll try to individually go through the yaml file over the coming week to see if I missed anything. 

> I also created a mapping for ISO script and, where needed, language codes for Aksharamukha. This is something that would be useful to have upstream, somehow — a mapping to script and language codes from/to the custom keywords you’re using.

That;s amazing! I always wanted to do this mapping. Thanks for doing this! Much appreciated.  I will incorporate this yaml to the Python package (and the web UI).  

Thanks again!

Vinodh

**Comment by twardoch** [comment]
Let me do some reworking of the YAML, and many thanks for the feedback!

**Comment by twardoch** [comment]
I realize that not all scripts are really suitable for Sanskrit. I need some reasonable test texts for various scripts, and I thought the transliterated Sanskrit UDHR is sort of comparable, in a way, to the Latin-language UDHR for European readers. It's better then nonsense. Just like you could write a Latin text in Cyrillic (though hardly anybody does that), I guess a similar "feeling" can be achieved with the Sanskrit UDHR transliterated into various scripts. Would you agree? :)

**Comment by virtualvinodh** [comment]
@twardoch Yeah. That makes sense. The users would at least be able to recognize at least some words :)

V

**Comment by virtualvinodh** [comment]
@twardoch I am not able to access your mapping file. Have you removed the code from your branch?

V

**Comment by twardoch** [comment]
Moved it: https://github.com/twardoch/udhr-custom/blob/main/tools/aksharamukha-scripts.yml

**Comment by twardoch** [comment]
BTW, you may be interested in taking a look at https://github.com/twardoch/wiktra2

**Comment by virtualvinodh** [comment]
@twardoch wiktra2 is brilliant!

I can re-use some much of the code (particularly in terms of language tags and script tags). I wanted to add the ability to perform Bengali transcription, it seems it has also already been implemented.

It would make sense if I could add to aksharamukha a new output format, _Roman (Wiktionary)_, to perform romanization according to the native rules. Currently, everything gets romanized as if it is Sanskrit. 

Thanks again for maintaining it!

Vinodh

**Comment by twardoch** [comment]
Wiktra2 is mostly in Lua (so it's not as portable as your tool) but I plan to add https://pypi.org/project/langcodes/ to work with both Aksharamukha and Wiktra. I’ll try to make sure that you can easily incorporate it into your code.

**Comment by twardoch** [comment]
Ps. I think it's of paramount importance that a translit API allows to specify just script, just language, lang+script for Source and target, and also perhaps an "auto" thing for source.

**Comment by twardoch** [comment]
PS3. This https://github.com/rspeer/langcodes#comparing-and-matching-languages will be useful for some fuzzy matching of Lang/scr to whatever a translit tool (Akshara or Wiktra) supports

**Comment by twardoch** [comment]
OK, seems my https://github.com/twardoch/wiktra2 is kind of working: 

```
$ wiktrapy -t "𐪑 𐪈 𐪔 𐪕 𐪂|𐪀 𐪅 𐪘 𐪖 𐪉 𐪚 𐪋 𐪁 𐪃 𐪌 𐪏 𐪒 𐪐 𐪎|𐪓 𐪄 𐪇 𐪊 𐪗 𐪒𐪕"
ʾ b g d ḥ|h w z ġ t y k l m n s³ ʿ f ṣ|ḍ q r s¹ ṭ ʿd

$ wiktrapy -t "𐡠 𐡡 𐡢 𐡣 𐡤 𐡥 𐡦 𐡧 𐡨 𐡩 𐡪 𐡫 𐡬 𐡭|𐡮 𐡯 𐡰 𐡱 𐡲 𐡳 𐡴 𐡵 𐡶 𐡰𐡣"
ʾ b g d h w z ḥ ṭ y k l m n|n s ʿ p ṣ q r š t ʿd

$ wiktrapy -t "𐭠 𐭡 𐭢 𐭣 𐭤 𐭥 𐭦 𐭧 𐭨 𐭩 𐭪 𐭫 𐭬 𐭭 𐭮 𐭥 𐭯 𐭰 𐭬 𐭥 𐭱 𐭲 𐭥𐭣"
ʾ b g d h ʿ z ḥ ṭ y k l m n s ʿ p c m ʿ š t ʿd
```

Has auto-script matching, if language is not supplied, chooses the most populous language for a given script (e.g. `ru` for `Cyrl`). Mapping of ISO codes to the Wiktionary transliteration module is semi-automatically built and stored in a [JSON/YAML](https://github.com/twardoch/wiktra2/blob/master/wiktra/wikt/data/data.yaml).

**Comment by virtualvinodh** [comment]
@twardoch 

I like this. So, if I attempt to transliterate a text marked as Hindi, I can automatically remove Schwa in the output. I can do tiny tweaks based on the input (or output) language. If someone marks a text as Marathi or Nepali, I can recognize that is written in Devanagari and transliterate it accordingly. 

Would be super useful to implement it. I will find some time to do this.

Thanks again for posting all the resources. Much appreciated 👍 

Vinodh

**Comment by virtualvinodh** [comment]
@twardoch I'm currently working on making Aksharamuha accept a variety of inputs, lang tags, script tags, etc. 

I was looking at the _yaml_ file of Wikitra2.  I see there are two properties, _script_, and _script_iso_ . What is the difference between them? 

Vinodh

**Comment by twardoch** [comment]
Wiktionary uses some custom script tags, e.g. it uses the "script" "fa-Arab" to differentiate one module from another, "Arab". I think I’ve disregarded this difference, but there may still be some virtue in maintaining a difference, for example the Unicode script "Hani" is aliased by "Hans", "Hant", "Japa" and "Kore", and in fact "Japa" is an alias for "Hani"+"Hira"+"Kana". There’s also the issue of "Latf" (Latin Fraktur) and "Latin". There might theoretically be a custom Fraktur-script module for some language (e.g. German).

But my code doesn’t really rely on this distinction right now. :)

**Comment by virtualvinodh** [comment]
@twardoch  I see! Thanks :)

Also: I had look at your Semitic transliterator, looks amazing! 

How did you come with your Brahmi mapping to the Semitic abjads? based on phonology or paleography?

I was thinking since you have the mapping to Brahmi, I can easily use it as an intermediate script and support the Semitic scripts here. But I also am slightly worried if I am going out of scope by including more and more non-Brahmic scripts. But then, Ashoka also had inscriptions carved out in Aramaic :)

V

**Comment by twardoch** [comment]
Wikipedia actually has these nice tables: 

- https://en.wikipedia.org/wiki/Phoenician_alphabet
- https://en.wikipedia.org/wiki/Brahmi_script
- https://en.wikipedia.org/wiki/Aramaic_alphabet
- https://en.wikipedia.org/wiki/Proto-Sinaitic_script

It took me some time to aggregate them. Gimeltra uses a JSON where it does:

1. Does preprocessing (like splitting Unicode ligatures into constituent letters, and removing marks)
2. Try direct script-to-script correspondence per char
3. If not, uses a Latin intermediate
4. Tries to map the Latin into the target
5. If not, uses a Latin fallback (like going from shin (`ṣ`) so `s`) and tries that. It also falls back from `f` to `p`.

**Comment by twardoch** [comment]
Ps. My Gimeltra is quite primitive at this point, but I agree that the idea of using a bridge script would be nice. :) 

I actually finished a better Wiktra API so I could perform some mappings to produce/improve my Gimeltra tables :D I initially made a table by hand but then supplemented it with Gimeltra. 

Of course this approach largely works for abjads only. When you add vowels, it instantly becomes much more complex :)

**Comment by virtualvinodh** [comment]
>  When you add vowels, it instantly becomes much more complex :)

Don't I know. There is so much pre-and post-processing with Indic scripts, I half forget what they do after I write the code.

> Of course, this approach largely works for abjads only.

I understand. 

I was thinking the following.

If someone wants to convert say Devanagari to Aramaic, I suppose we can ignore the short vowels and use Mater Lectionis to denote the long ones. For the reverse, we can just provide a consonantal reading (you already do it with Brahmi).

V

**Comment by twardoch** [comment]
OK, I finally managed to do what I set out to do — have the UDHR in some ancient scripts. So I have "Assyrian Neo-Aramaic (Hatran)" etc. :) This is of course not really very sensible, but at least it’s not nonsense. :)

**Comment by twardoch** [comment]
BTW, it seems that the bridge from Phoenician descendents to Brahmi and Devanagari is phonetic in https://en.m.wikipedia.org/wiki/Phoenician_alphabet — which makes sense of course

**Comment by twardoch** [comment]
One tip for your work: my Gimeltra and Wiktra transliteration codes follow a simple OpenType glyph processing model (but with Unicode characters): 

In Gimeltra, I have preprocessing with a "ccmp" table (splitting ligatures into single chars), then "csub" (character substitutions), then postprocessing with "fina" (positional forms, right now only final letters) and then "liga" (ligature letters). Here I don’t deal with any language-specific info right now but I might in future. 

In Wiktra, which of course does the actual conversion using Lua, I’ve used a different aspect of OpenType. 

An OpenType layout engine first itemizes Unicode text into "runs" which are per script. So the script of the text is always known. Then inside fonts, glyph substitution & positioning features (GSUB, GPOS) are stored per script, and always the correct script-specific branch of the features is applied to the run.  

Inside a script record of an OpenType font, there is a record for the default languagesystem ("DFLT") and optionally language-specific records (tagged using OT language tags which are a bit different from ISO 639 tags for historical reasons. If the language of the text is explicitly known and language-specific records are present, those are applied, otherwise the default records for the script are applied. 

The equivalent of the "DFLT" OT languagesystem is the ISO 639 "und" language code (undefined language). I didn’t think of the "und" ISO 639 code much before, but it’s very handy. Any script-generic rules can be associated with the "und" language tag. Within a data structure, other language tags would only be present if a different set of rules is desired. Otherwise, the API should fall back to the "und" language rules. 

This is how I more-less did the data table in Wiktra. So ultimately, the data table always has an input_script record, then the input_language record (using "und" as default), then output_script, then could also use output_lang, again with "und". 

That approach would be standards-compliant, and in fact, would be compatible with OpenType — so one could imagine that a transliterate feature could be synthethized from such data and stored in a font’s GSUB record (not that this would make much sense, because it’s not a good idea to make features that mimic Unicode script transformations, but at least in principle, it’s doable :) ).

**Comment by virtualvinodh** [comment]
@twardoch I have added support for language and script tags.

I

> nstead of using Aksharamukha's identifiers, you can also the respective ISO codes (ISO 15924 for scripts and ISO 639-1 or ISO 639-1 for languages).
> 
```
transliterate.process('deva', 'taml', 'धर्म भारत की ', param="script_code")
transliterate.process('te', 'ur', 'ధర్మ భారత', param="lang_code")
transliterate.process('odia', 'ho', 'ଧର୍ମ ଭାରତ', param="lang_name")
```
> 
> You would need to use the format lang_code-script_code to use scripts that have multiple orthographies (e.g. Arabic script for Urdu and Punjabi) or languages that can be written in multiple scripts (e.g. Punjabi written in Gurmukhi and Shahmukhi). For romanization, you can use the language code la-romanization_format or the script code latn-romanization_format as input.
```
transliterate.process('autodetect', 'latn-iast', 'धर्म भारत की ', param="script_code") 

transliterate.process('autodetect', 'pa-arab', 'धर्म भारत की ', param="script_code")

transliterate.process('la-HK', 'pa-guru', 'namo buddhAya', param="lang_code")
```

**Comment by virtualvinodh** [comment]
@twardoch I still want to integrate gimeltra into Aksharamukha. I'll keep this issue open until it is done.
