### ISSUE TITLE
Using Aksharamukha as a Language learning tool

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#14]
Convert these web sites in to your chosen script to learn a stated  language or to get a correct transliteration in IAST scheme.
http://learn101.org/tamil_voc500.php
https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Hindi_1900

**Comment by virtualvinodh** [comment]
I don't understand. What do you expect from me exactly?

V

**Comment by geethub** [comment]
I initiated this thread to let users know that Aksharamukha is a very good tool for learning a language in correct phonetics. This tool is very good for above stated links.
