### ISSUE TITLE
Problem with Bengali preconsonantal t followed by v

### ISSUE THREAD

**Issue by chakrabortydeepro** [virtualvinodh/aksharamukha#140]
@virtualvinodh Dear Vinodh, I've been using and recommending Aksharamukha for several years. It's a wonderful tool. I just want to draw your attention to the problem with the use of Bengali preconsonantal _t_ when followed by _v_. 

Preconsonantal _t_ always becomes a **khaṇḍa t** (U+09CE) before _v_ (we don't have a real labio-dental _v_ in Bengali, but we can consider the _tatsama_ words here) as in কবিত্ব _(kavitva)_ . But in Aksharamukha, if I give the input with _b_ instead of _v_  it shows the desired form (kabitba > কবিত্ব) but when with _v_, it shows the _khaṇḍa ta_ (kavitva > *কবিৎব) instead, which is not correct. 

Could you please fix it? If you really want to show a difference in these consonant clusters I guess it is better to make it opposite i.e. **tb > ৎব্** and **tv > ত্ব্** . We cannot have tb combinations in Sanskrit words in Bengali but in other words we sometimes find this combination as in the word কৎবেল (katbel). And if we write any foreign word which has a consonant cluster of _t_ and _b_ we would write it with the _khaṇḍa ta_. But Sanskrit "tv" combinations are never rendered with the "khaṇḍa ta" in Bengali.

**Comment by jups23** [comment]
@chakrabortydeepro I just had the same issue!

- Roman IAST "tattva" becomes "তত্ত্ব" (correct)
- Roman IAST "tviṣā" becomes "ৎবিষা" (wrong). Instead, it should be "ত্বিষা"

This fix would be important to convert Sanskrit texts to Bengali letters because t+v occurs frequently in Sanskrit texts due to the sandhi of "tu" with any consonant becoming "tv".

**Comment by virtualvinodh** [comment]
@chakrabortydeepro Thanks for letting me know. 

I figured out why this is happening. It should be easy enough to fix it.

I convert kavitva to কৱিৎৱ and then replace all instances of ৱ with ব.

IIUC: 

tva -> ত্ব
tba -> ৎব

Or would it make sense to convert both tva & tba as ত্ব?

Is that right?

Vinodh

**Comment by chakrabortydeepro** [comment]
Thanks for fixing the problem, Vinodh.
tva -> ত্ব
tba -> ৎব
I think this option is better. Then we can accurately translierate words
like কৎবেল and any other foreign words which have the consonant cluster
"tb".

**Comment by virtualvinodh** [comment]
@chakrabortydeepro Also: Do you have any pointers to this? https://github.com/virtualvinodh/aksharamukha/issues/65

Just some rules of thumb might help.

V

**Comment by virtualvinodh** [comment]
I have fixed this. Please have a look!

V

**Comment by chakrabortydeepro** [comment]
Looks perfect. Thanks!
