### ISSUE TITLE
Fix Urdu Dipthongs

### ISSUE THREAD

**Issue by virtualvinodh** [virtualvinodh/aksharamukha#141]
From email:

<<for Urdu script in Aksharamukha app, you have placed ء to separate two vowels which is wrong. It should be ئ instead. See the attachment please.>>

![Screenshot_٢٠٢١٠٧٢٤-١٦٢٢٣٨_Aksharamukha](https://user-images.githubusercontent.com/1050975/126898300-1952173f-fa83-4285-bfd8-f661805491a2.jpg)

![Screenshot_٢٠٢١٠٧٢٤-١٦٢٢٣٠_Aksharamukha](https://user-images.githubusercontent.com/1050975/126898303-7831d6b9-0649-4888-8b40-14b754a6a413.jpg)

**Comment by GokulNC** [comment]
> It should be ئ instead.

It's actually more complex than that..
This might help in-case you're fixing this:
https://en.wikipedia.org/wiki/Hamza#Overview_tables

ۓ also needs to be handled for Shahmukhi/Urdu izafat.

**Comment by virtualvinodh** [comment]
@GokulNC Thanks! That's useful!

V

**Comment by virtualvinodh** [comment]
http://www.columbia.edu/~mk2580/urdu_section/handouts/hamza.pdf
