### ISSUE TITLE
Preserve source - Thaana & Perso-Arabic consonants

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#142]
Is it possible to preserve source for Dhivehi & Urdu consonants which are of Perso-Arabic origin?

For your reference:

|Thaana|Perso-Arabic|Devanagari|Roman|
|-|-|-|-|
|ޙ‎|ح|ह़|h̤|
|ޜ|ژ|झ़|ž|
|ޘ‎|ث|थ़ / स़़|ṯ / s̱|
|ޛ‎|ذ|द़ / ज़़|ḏ / ẕ|
|ޞ‎|ص|स़|s̤|
|ޟ‎|ض‎|ध़ / ॹ|ḋ / ż|
|ޠ‎|ط‎|त़|t̤|
|ޡ‎|ظ|ध़़ / ॹ़|d̤ / z̤|
|ޥ||व़|w|

Please note that:
- Some Devanagari consonants are approximately made-up to enable one-to-one map
  (some with multiple nuqtas, though it may not be separately visible in default font)
- Some phonemes are transcribed differently in Arabic (as in literary Dhivehi) and Persian (as in Urdu)

I might have missed something, please feel free to implement it the way you see it right.
Thanks!

---

Edit: Suggestions for Thaana--
- For diphthongs (like ޤައުމަކަށް -> qa:umakaṣ), please use the _U+A789_ colon instead of the regular colon.
- For word final /އް‎/, please use _U+02BE_ instead of ʔ

**Comment by virtualvinodh** [comment]
@GokulNC Thanks for this!

Isn't there a way to uniquely (as in one-to-one) transcribe Urdu to Devanagari? I am sure somebody should have done standardized mapping. 

V

**Comment by GokulNC** [comment]
So far I haven't come across any standardizations/proposals to uniquely map all Perso-Arabic consonants to Devanagari.
I think this is mainly because there is no necessity to do that. Only when it comes to lossless transliteration (for computational purposes), it might make sense to have such a map.

For example, there are 4 graphemes in Persian & Urdu (ز , ذ , ض , ظ) for the same phonetic (IPA /z/) , for which the Devanagari "ज़" is sufficient. Similarly for स, त, ह. 

Some of the above consonants in table (ह़/ح, झ़/ژ, थ़/ث, स़/ص, त़/ط‎) comply with the latest ISO 15919 Indic Transliteration standard.

---

There seems to have been some established mapping for Hindustani which I came across in the book:
_The Hindee-Roman Orthoepigraphical Ultimatum_ ([See pages cxxxvi & cxxxvii](https://books.google.co.in/books?id=zFIIAAAAQAAJ&printsec=copyright))

This features the double-nuqta स for ث (`स़़` - Shows 2 nuqtas in some fonts)
I am not sure about the other Nagari characters listed for the unique mapping (does not seem to be in modern Devanagari)

**Comment by GokulNC** [comment]
For Mahl Dhivehi (of Lakshadweep), I found this mapping for Devanagari:
https://en.wikipedia.org/wiki/Maldivian_writing_systems#/media/File:Mahldevanagari.png
(See additional consonants section in the image)

Not sure of its origin and authenticity.

**Comment by virtualvinodh** [comment]
Fixed. Will be available in the next update. 

I had to make up my own mapping a bit but this should work.

You have to enable preserve script to access the extra nuktated consonants.

V
