### ISSUE TITLE
[wish] Nandinagari support

### ISSUE THREAD

**Issue by twardoch** [virtualvinodh/aksharamukha#144]
Any chance that you might add support for the [Nandinagari](https://en.wikipedia.org/wiki/Nandinagari) script? :)

**Comment by virtualvinodh** [comment]
Sure. Once I power through the two dozen issues raised before this :)

Is there a Noto Sans Nandinagari in the plans yet?

Vinodh

**Comment by twardoch** [comment]
I can neither confirm or deny but I can say that I tend not to ask people to do work in vain ;) :)

**Comment by virtualvinodh** [comment]
Then, I better start re-reading Anshuman's proposal ;)

**Comment by virtualvinodh** [comment]
This has been added.
