### ISSUE TITLE
Agastya Serif ligated u-matra

### ISSUE THREAD

**Issue by vbharadvaja** [virtualvinodh/aksharamukha#147]
Namaskaram sir,

The ligated style u-matras don't seem to render on the Agastya Serif font. Would it be possible to add them? 

🙏🏼🙏🏼

**Comment by virtualvinodh** [comment]
Sorry. I don't think so. I pretty much invented them just for experimentation.  There is at least one font that supports them if you'd like to use them.

**Comment by vbharadvaja** [comment]
Oh, ok sir. I had found them to be a lot more aesthetically appealing than the Grantha style u-matras. Guess I should start learning how to make fonts now 😅😅

**Comment by virtualvinodh** [comment]
@vbharadvaja 

Please do :)

V
