### ISSUE TITLE
Brahmi font adjustment for readability

### ISSUE THREAD

**Issue by Geochiraltax** [virtualvinodh/aksharamukha#149]
This isn't really an issue with Aksharamukha, but I couldn't find a better place to post this issue anyway (if someone thinks I should post this elsewhere, please let me know).

In both Noto Sans Brahmi and Segoe UI Historic, Brahmi letters 𑀚𑁂 ( IAST: je) and 𑀚𑁄 (IAST: jo) have a very minute difference, which is barely noticeable for humans to read, and can even be wrongly interpreted when reading a printed text. Same is the case with 𑀚𑁃 (IAST: jai) and 𑀚𑁅 (IAST: jau)

Historically, the font might be correct but I have an alternate forms in my mind, based on the logic that the diacritic sign for 'o' is usually formed by combining the 'e' and 'ā' signs, which look like this:

 
![image](https://user-images.githubusercontent.com/19777432/128633419-3d17b87d-eee1-4334-bb8f-38624ea3eb48.png)

![image](https://user-images.githubusercontent.com/19777432/128633433-202bc981-220d-47c3-8e7a-b779ccf753ac.png)

Is there a way to modify the font so that I can use these new forms? Or is there anything that can be done in Aksharamukha so the change is global (if more people are willing to see this change)?

**Comment by virtualvinodh** [comment]
@Geochiraltax 
 
Yes. Technically, Noto Sans Brahmi is under an open-source license. So, you can do whatever you want with it.

I mean, the forms you proposed seem to be attested (according to Indoskript). So, I don't see a reason why this shouldn't be done. I would get font forge (or any font editor for that matter) and start editing the font.  But then Noto Sans Brahmi is pretty useless as it almost contains no conjuncts and several other issues.

Then, we might as well start forking the font and fixing all of the issues while we are editing it :)

V

**Comment by Geochiraltax** [comment]
> ![image](https://user-images.githubusercontent.com/64453040/138707210-eae31b73-3a97-4bfe-b20d-20a1362d28e3.png) [jaa, jo, jau] Isn't it already such in Google's Noto Sans Brahmi

Noto Sans Brahmi doesn't seem to support as many ligatures as Segoe UI Historic, though.

**Comment by virtualvinodh** [comment]
I am closing this as there isn't much I can do.

A better solution as suggested would be to fork Noto Sans Brahmi and fix the relevant issues. or better raise a bug with Noto Fonts.

https://github.com/googlefonts/noto-fonts/issues

V
