### ISSUE TITLE
[RFE] Few updates to Bengali (Bangla)

### ISSUE THREAD

**Issue by akarshanbiswas** [virtualvinodh/aksharamukha#150]
As we discussed on Twitter:
* Please add option to use the old Bengali ৰ alongside the modern Post ICV's reformation র 
* Please move the Assamese loan letter ৱ to another option and use diacritic numbers or any markers similar to Tamizh when "Preserve Source" option is enabled as the default behaviour.
For example:
ba = ব 
va = ব²

Also an option to disable diacritic numbers will be good. :)

**Comment by virtualvinodh** [comment]
@akarshanbiswas 

Thanks!

So, Assamese /ৱ/ is never used in Bengali (even to preseve va/ba distinction) ?

Vinodh

**Comment by akarshanbiswas** [comment]
Actually Assamese used র for va. ৱ is the modern form.
But in the book "A grammar of Bengali language, 1778 by Nathaniel Brassey Halhead" shows this
![Halhed_alphabet](https://user-images.githubusercontent.com/17230826/128699940-cf64d7a9-4aab-43e6-b337-fc8eb4cfb279.png)

It's better to put them in separate options imo.

Also native Assamese pronunciation of the letters is different from Bengali pronunciation.
For example, An Assamese reading of চৰকাৰ is sorkaar[a], whereas the same reading in Bengali is corkaar[a].

**Comment by GokulNC** [comment]
It looks like /ভ়/ (bha with nuqta) can be used in Bengali for /v/ , according to most transliteration schemes:
https://en.wikipedia.org/wiki/Romanisation_of_Bengali#Additional_Consonants

**Comment by GokulNC** [comment]
Also, Bengali should not delete the schwa for words that end with a consonant cluster (when the pre-processing flag `SchwaFinalBengali` is enabled)

For example, "অন্ত" should be "anta" and "পথ" should be "path" (where 'a' is Bengali schwa 'ô' when transcribed).
Source: [Wiki](https://en.wikipedia.org/wiki/Schwa_deletion_in_Indo-Aryan_languages#Bengali)

**Comment by milindchakraborty** [comment]
> Also, Bengali should not delete the schwa for words that end with a consonant cluster (when the pre-processing flag `SchwaFinalBengali` is enabled)
> 
> For example, "অন্ত" should be "anta" and "পথ" should be "path" (where 'a' is Bengali schwa 'ô' when transcribed). Source: [Wiki](https://en.wikipedia.org/wiki/Schwa_deletion_in_Indo-Aryan_languages#Bengali)


Except for foreign loans. লিস্ট, বেস্ট, কাল্ট, বাল্‌ব, কার্ট, পার্ক, টেন্ট, etc.


Also I mentioned about the usage of ব and ৰ in Bangla in the thread...

[Issue 173](https://github.com/virtualvinodh/aksharamukha/issues/173) 

> Ramakrishna Mission (Udbodhana Karyalaya) way of  Sanskrit transcription uses ৰ for writing b in Sanskrit as opposed to ব for w. 

> যা দেবী সর্বভূতেষু ৰ‌ুদ্ধি রূপেণ সংস্থিতা।
> নমস্তস্যৈ॥ নমস্তস্যৈ॥ নমস্তস্যৈ॥ নমো নমঃ॥
> या देवी सर्वभूतेषु बुद्धि रूपेण संस्थिता।
> नमस्तस्यै॥ नमस्तस्यै॥ नमस्तस्यै॥ नमो नमः॥

> But there are some quirks,
> बु is ৰ‌ু not ৰু
> बू is ৰ‌ূ not ৰূ

> The compounds are, ম্‍ৰ in সম্‍ৰন্ধ (संबंध) not সম্ৰন্ধ, ब्रूहि will be ৰ‍্ৰূহি, ब्य will be ৰ‍্য, ब्ब will be ৰ্‌ৰ (honestly should look like ব্ব, but I don't know if that's doable), ब्ल will be ৰ‍্ল (honestly should look like ব্ল but is that doable in Unicode) ब्ध will be ৰ্‌ধ (should actually look like ব্ধ), ब्ज should be ৰ্‌জ (should actually look like ব্জ) etc. It behaves like ব in conjuncts basically.

> ![20220224_193116](https://user-images.githubusercontent.com/64827324/155539300-915b0efe-1662-4e21-a9ce-15fd46570b98.jpg)
> ![20220224_193144](https://user-images.githubusercontent.com/64827324/155539311-4bcedfb6-b21d-48f8-90e2-106349e6d8c8.jpg)
> ![20220224_193241](https://user-images.githubusercontent.com/64827324/155539319-5f0346cf-599e-4fa6-8e71-b68199e16e67.jpg)
> ![20220224_193404](https://user-images.githubusercontent.com/64827324/155539322-b4edc927-456f-4467-a476-1835427a923d.jpg)

**Comment by GokulNC** [comment]
> Except for foreign loans. লিস্ট, বেস্ট, কাল্ট, বাল্‌ব, কার্ট, পার্ক, টেন্ট, etc.

In rule-based systems (like aksharaMukha), it's not generally possible to find which words are native or foreign. Hence we'll have to make the assumption that foreign words are also assimilated as per the transcription scheme of the target language.

**Comment by virtualvinodh** [comment]
Fixed: 

Option for /v/ to /ভ়/
And another option for Bengali old style ra /ৰ/

V

**Comment by virtualvinodh** [comment]
It will be available when I release the next update. Hopefully, before the end of May.
