### ISSUE TITLE
Tamil Post-processing for reformed vowels au,ai and Grantha consonants

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#151]
For independent vowels ஐ and ஔ , would it be possible to add a post-processing option to convert them to அய் and அவ் respectively? (not necessary for dependent vowels I guess)

For the 5 Grantha consonants also, is it possible to add another post-processing flag to convert them to the nearest core consonants?
(Or possibly with a superscript number near those consonants like the numbering for voiced & aspirated consonants)

Thanks!

**Comment by thevaram-class** [comment]
I presume you mean word beginning ai & au (ஐ & ஔ) letters only.
You are seeking this where Tamil is the target language?
So, something like ऐश्वरय becomes அய்ஸ்வர்ய in Tamil? 
And औषदम् becomes அவ்ச5த3ம் ?
What is the intended use case? Just curious.

**Comment by virtualvinodh** [comment]
Tamil has already a dozen options. It is very unlikely I am gonna add this. I don't it seeing used as much (nor do I want it to be used).

Sorry!
