### ISSUE TITLE
Malayalam pre-processing flag to convert word-final virama to half-u

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#152]
To transcribe Malayalam, it would be helpful to add a flag which would convert the word-final virama as half-u or full-u, whichever is feasible.

For example, അവൻ (with chillu) is transliterated correctly as _avan_, but അവന്‌ is also converted as _avan_ which actually should have been _avanŭ_ or _avanu_. (The transcription can either be to അവനു് or അവനു as in Tamil)

Also please note that Devanagari has support for half-u (as in Kashmiri), like: अवनॖ .
Or you can probably keep it simple as अवनु् / அவனு் when preserve source is enabled (though it looks weird)

More info: https://en.wikipedia.org/wiki/Malayalam_script#Chandrakkala

---

If possible, you can also consider a similar transcription flag for Tamil (if that will be helpful).
More details: https://ta.wikipedia.org/wiki/குற்றியலுகரம்

**Comment by virtualvinodh** [comment]
This has been implemented. Fill be available when I push the new version.

I am vary of using the Kashmiri vowel signs as it would be alien to most people. I have retained u + virama, even thouh it's wierd at least it's readable.

V
