### ISSUE TITLE
Sanskrit to Pali Experimental Transformation

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#153]
It just felt to me that it would be an interesting experiment to transform Sanskrit texts (in Devanagari) to Pali literary form.

Although not exhaustive, this conversion seems to be good enough:
https://en.wikipedia.org/wiki/Pali#Conversion_between_Sanskrit_and_Pali_forms

That is, it would be wonderful to have a post-processing option for Roman-Pali to convert from Sanskrit to Pali-like forms.
(Or probably a pre-processing option for Devanagari?)

Please feel free to close this issue if it might not be relevant here. :)
(Although it looks a bit tedious, I am planning to try this out one day)

**Comment by virtualvinodh** [comment]
@GokulNC I feel like we are expanding the scope too much :)

I will keep it open for now. It is an interesting exercise after all. We could adding "Prakritification" Sanskrit texts based on different standards/periods/conventions. My understanding is that (I remember reading it somwhere) even the Prakrits that appear in (some?) Sanskrit plays are somehow just mechanical transformations of the underlying Sanskrit.

You may want to see this as well. Somebody already tried this 12 years ago  (albeit manually) :))

http://www.theravadin.org/2009/02/19/when-mahayana-started-as-a-reformation/

Vinodh

**Comment by GokulNC** [comment]
> You may want to see this as well. Somebody already tried this 12 years ago

Interesting read :) thanks...

Looks like a perfect Sanskrit to Pali conversion would not just involve rule-based transformations, but also usage of slightly different vocabulary. Also, I guess by just following a mechanical transformation, there would be some words where the result will not be Pali-like, since they might be derived from the original literary Magadhi Prakrit vocabulary (which probably can be captured by slightly different transformations?). The manual transformation in his article seems to be involving knowledge of both Pali and Sanskrit vocabulary forms, which I think is difficult in general.

>  We could adding "Prakritification" Sanskrit texts based on different standards/periods/conventions.

Yes, Prakritification in general is interesting, but seems very broad and I am not sure if there would be transformations easily available for all of them, except probably Jaina Prakrit. Sanskrit being a cross-regional literary language in general, regional Prakitifications are common I guess, especially in plays as well as sramanic literature. It actually quite surprises me how some Prakrit words have even entered Tamil and have become part of the daily usage vocabulary (like _sattham_, from Sanskrit _shabdam_).

> I feel like we are expanding the scope too much. I will keep it open for now.

Sure, please feel free to close any of my issues anytime. :)
