### ISSUE TITLE
தடங்கடல் - bug in Tamil transcription to other languages

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#154]
A new bug is noticed in the transcription of Tamil to other languages. In some situations, the tool is adding superscripts after some letters in the target language! See the example below.

தடங்கடல்
taḍaṅgaḍa³l
तडङ्गड³ल्
తడంగడ³ల్

But if I slightly modified the Tamil word - this issue does not appear - and it is transcribed correctly!
தடங்-கடல்
taḍaṅ-gaḍal
तडङ्-गडल्
తడఙ్-గడల్
-----------------

Similar issue noticed in the following word too.
சிங்கடி
siṅgaḍa³i
सिङ्गडि³
సింగడి³
-------------

Some other example combinations - with and without this issue:
சங்கதி ==> saṅgada³i
சகதி ==> sagada³i
கதி ==> kadi -- (OK)

சங்கடம் ==> saṅgaḍa³m
சகடம் ==> sagaḍa³m
கடம் ==> kaḍam -- (OK)
-------------

So, my guess is that some specific combination(s) of letters is triggering this issue.

**Comment by virtualvinodh** [comment]
Aah! I found out the issue.

I have pushed a fix. Could you please try again?

Vinodh

**Comment by thevaram-class** [comment]
Thanks. I just checked with words like the following. The issue no longer occurs. Thank you.
தடங்கடல்
தடங்-கடல்
விடங்கன்
தங்குதல்
தம் கடன்
கடல் 

taḍaṅgaḍal
taḍaṅ-gaḍal
viḍaṅgan
taṅgudal
tam kaḍan
kaḍal 

பகுதி
சகதி
சங்கதி
கந்தன்

pagudi
sagadi
saṅgadi
kandan
