### ISSUE TITLE
Issue with full stop (period) in Roman (ISO 15919) to Devanagari.

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#156]
When I convert from Tamil to Roman (ISO 15919), Devanagari etc. - I often manually tweak the Roman (ISO 15919) converted text (for pronunciation for some exceptions - such as தேவன், குணம், etc.).
When I use that tweaked Roman text for further conversion to Devanagari, the full stop (period) becomes a vertical bar.
Is there any way to control and retain the period in the target text?

Source text - for testing:
1.2.3
கூற்றுதைத்த கோன்.
kūṭrudaitta kōn.

When I use - Source Tamil (transcribe flag on) & Target Devanagari: it is converted correctly (as I expect):
1.2.3
कूट्रुदैत्त कोन्.
kūṭrudaitta kōn.

When I use - Source Roman (ISO 15919) & Target Devanagari: it is converted as:
१।२।३
கூற்றுதைத்த கோன்।
कूट्रुदैत्त कोन्।

In the above, the period has become a vertical bar.

**Comment by virtualvinodh** [comment]
I would suggest that you use 

https://aksharamukha.appspot.com/composer

And mark the Tamil text as "don't convert" using # 

![image](https://user-images.githubusercontent.com/1050975/167511367-4d0aa3be-5c68-400b-bc27-4322c10745fe.png)


V

**Comment by thevaram-class** [comment]
Hi Vinodh,

So you are suggesting that I treat the "1.2.3" as a string that should not
be converted by manually specififying it as "#1.2.3#" .
That way, the converted string will still be "1.2.3" instead of "१।२।३" ?

**Comment by virtualvinodh** [comment]
Yup.

And use the composer rather than the converter.

Cheers,

V
