### ISSUE TITLE
Documenting Roman (Readable) + Roman (Colloquial)

### ISSUE THREAD

**Issue by the-solipsist** [virtualvinodh/aksharamukha#158]
Hi. I haven't yet come across documentation of Roman (Readable) and Roman (Colloquial). So I thought I'd try to create a mapping using Devanagiri (and comparing them to the Aksharaa romanization input scheme).

Perhaps some part of this could be reflected on the website somewhere?

Devanagiri | Roman (Readable) | Roman (Colloquial) | Aksharaa
-- | -- | -- | --
ऀ |  | |  
ँ | m' | m | m;
ं | m | m | m'
ः | h' | h | h'
ऄ |  |  |  
अ | a | a | a
आ | aa | a | aa
इ | i | i | i
ई | ee | i | ii
उ | u | u | u
ऊ | oo | u | uu
ऋ | ri' | ri | ru'
ऌ | li' | li | lu'
ऍ | a | a | ee'
ऎ | e' \| e | e | e
ए | e \| ae | e | ee
ऐ | ai | ai | ai
ऑ | o \| oa | o | o'
ऒ | o' \| o | o | o
ओ | o \| oa | o | oo
औ | au | au | au
क | ka | ka | ka
ख | kha | kha | kha
ग | ga | ga | ga
घ | gha | gha | gha
ङ | nga | nga | ng'a
च | cha | cha | cha
छ | chha | chha | chha
ज | ja | ja | ja
झ | jha | jha | jha
ञ | nya | nya | nj'a
ट | t'a | ta | t'a
ठ | t'ha | tha | t'ha
ड | d'a | da | d'a
ढ | d'ha | dha | d'ha
ण | na | na | n'a
त | ta | ta | ta
थ | tha | tha | tha
द | da | da | da
ध | dha | dha | dha
न | na | na | na
ऩ | na | na | n;a
प | pa | pa | pa
फ | pha | pha | pha
ब | ba | ba | ba
भ | bha | bha | bha
म | ma | ma | ma
य | ya | ya | ya
र | ra | ra | ra
ऱ | r'a | ra | r'a
ल | la | la | la
ळ | l'a | la | l'a
ऴ | zha | zha | zha
व | va | va | va
श | sha | sha | sha
ष | sha | sha | shha
स | sa | sa | sa
ह | ha | ha | ha
ऺ |   |   |  
ऻ |   |   |  
़ |   |   |  
ऽ | ' |   | a;
ा | aa | a | aa
ि | i | i | i
ी | ee | i | ii
ु | u | u | u
ू | oo | u | uu
ृ | ri' | ri | ru'
ॄ | ree' \| raee | ri | lu'
ॅ | a | a | ee'
ॆ | e' \| e | e | e
े | e \| ae | e | ee
ै | ai | ai | ai
ॉ | o \| oa | o | o'
ॊ | o' \| o | o | o
ो | o \| oa | o | oo
ौ | au | au | au
् |   |   |  
ॎ | e \| ae | e |  
ॏ |   |   |  
ॐ | om \| oam | Om | oom'
॑ |   |   | \\'
॒ |   |   | \\_
॓ |   |   |  
॔ |   |   |  
ॕ | e \| ae | e |  
ॖ | u'‌ | u‌ |  
ॗ | oo‌ | u‌ |  
क़ | qa | qa | qa
ख़ | kha | kha | qha
ग़ | ga | ga | g;a
ज़ | za | za | za
ड़ | ra | ra | d;a
ढ़ | rha | rha | d;ha
फ़ | fa | fa | fa
य़ | ya | ya | y;a
ॠ | ree' \| raee | ri | ruu'
ॡ | lee' \| laee | li | luu'
ॢ | li' | li |  
ॣ | lee' \| laee | li |  
। | . | . | .
॥ | .. | .. | ..
० | 0 | 0 | 0
१ | 1 | 1 | 1
२ | 2 | 2 | 2
३ | 3 | 3 | 3
४ | 4 | 4 | 4
५ | 5 | 5 | 5
६ | 6 | 6 | 6
७ | 7 | 7 | 7
८ | 8 | 8 | 8
९ | 9 | 9 | 9
॰ |   |   |  
ॱ |   |   |  
ॲ | a | a |  
ॳ |   |   | a\\' 
ॴ |   |   | aa\\'
ॵ |   |   |  
ॶ | u'‌ | u‌ |  
ॷ | oo‌ | u‌ |  
ॸ |   |   |  
ॹ | za | za |  
ॺ |   |   |  
ॻ | ˍga | ˍga | ga\\_
ॼ | ˍja | ˍja | ja\\_
ॽ |   |   |  
ॾ | ˍd'a | ˍda | d'a\\_
ॿ | ˍba | ˍba | ba\\_

**Comment by virtualvinodh** [comment]
@the-solipsist Yeah. I missed it.

I'll add this in the next updae. Thanks for letting me kno!

V

**Comment by virtualvinodh** [comment]
This has been done.
