### ISSUE TITLE
RFE: Rich Tamil Notation

### ISSUE THREAD

**Issue by laksri** [virtualvinodh/aksharamukha#159]
![SmartSelect_20210924-204026_Xodo Docs](https://user-images.githubusercontent.com/7048700/134752038-4e310205-5f18-49c2-b8ef-634a9d56db1b.jpg)
Request for supporting rich Tamil notation for devanagari equivalents.

**Comment by virtualvinodh** [comment]
There are a dozen variations of representing Sanskrit in the Tamil script. I am not inclined to support all of them in favor of making superscript/subscript numeral notation.

V
