### ISSUE TITLE
IAST to IPA transliteration based on vowels only

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#16]
English consonants' pronunciations are easily understood by people but not vowels in the words. We need only IPA's vowels in Roman transliteration to teach vernacular languages in Roman script. 

IAST:
Eka samaya thā jaba mahātmā gāṃdhī aura vinobā bhāve jaise svataṃtratā senānī rāṣṭrīya ekatā kī dṛṣṭi se rāṣṭrabhāṣā ke rūpa meṃ hiṃdī aura rāṣṭrīya lipi ke rūpa meṃ devanāgarī lipi ko sthāpita karane ke lie prayāsarata the. Yahām̐ taka ki śahīde āzama bhagata siṃha ne bhī apanī mātṛbhāṣā paṃjābī ke lie gurumukhī ke bajāe vaijñānikatā ke calate devanāgarī ko apanāne kī bāta kahī thī. Unakā prayāsa thā ki deśa ke jina hissoṃ meṃ denavāgarī pracalita nahīṃ haiṃ vahām̐ bhī jana-jana taka devanāgarī lipi pahuṃcāī jāe. Isalie mahātmā gāṃdhī va vinobā bhāve dvārā hiṃdī ke sātha-sātha devanāgarī lipi ke lie aneka saṃsthāem̐ khar̤ī kī thī.

IPA:
eːkə s̪əməjə t̪ʰɑː d͡ʒəbə məɦɑːt̪mɑː gɑ̃ːd̪ʰiː əuɾə ʋɪn̪oːbɑː bʰɑːʋeː d͡ʒəɪs̪eː s̪ʋət̪ə̃t̪ɾət̪ɑː s̪eːn̪ɑːn̪iː ɾɑːʂʈɾiːjə eːkət̪ɑː kiː d̪ɾɨʂʈɪ s̪eː ɾɑːʂʈɾəbʰɑːʂɑː keː ɾuːpə mẽː ɦɪ̃d̪iː əuɾə ɾɑːʂʈɾiːjə lɪpɪ keː ɾuːpə mẽː d̪eːʋən̪ɑːgəɾiː lɪpɪ koː s̪t̪ʰɑːpɪt̪ə kəɾən̪eː keː lɪeː pɾəjɑːs̪əɾət̪ə t̪ʰeː. jəɦɑ̃ː t̪əkə kɪ ʃəɦiːd̪eː ɑːzəmə bʰəgət̪ə s̪ɪ̃ɦə n̪eː bʰiː əpən̪iː mɑːt̪ɾɨbʰɑːʂɑː pə̃d͡ʒɑːbiː keː lɪeː guɾumukʰiː keː bəd͡ʒɑːeː ʋəɪd͡ʒɲɑːn̪ɪkət̪ɑː keː t͡ʃələt̪eː d̪eːʋən̪ɑːgəɾiː koː əpən̪ɑːn̪eː kiː bɑːt̪ə kəɦiː t̪ʰiː. un̪əkɑː pɾəjɑːs̪ə t̪ʰɑː kɪ d̪eːʃə keː d͡ʒɪn̪ə ɦɪs̪s̪õː mẽː d̪eːn̪əʋɑːgəɾiː pɾət͡ʃəlɪt̪ə n̪əɦĩː ɦəɪ̃ ʋəɦɑ̃ː bʰiː d͡ʒən̪ə-d͡ʒən̪ə t̪əkə d̪eːʋən̪ɑːgəɾiː lɪpɪ pəɦũt͡ʃɑːiː d͡ʒɑːeː. ɪs̪əlɪeː məɦɑːt̪mɑː gɑ̃ːd̪ʰiː ʋə ʋɪn̪oːbɑː bʰɑːʋeː d̪ʋɑːɾɑː ɦɪ̃d̪iː keː s̪ɑːt̪ʰə-s̪ɑːt̪ʰə d̪eːʋən̪ɑːgəɾiː lɪpɪ keː lɪeː ən̪eːkə s̪ə̃s̪t̪ʰɑːẽː kʰəɽiː kiː t̪ʰiː.

IPA(vowels only)
Ɛkə səməyə thɑː jəbə məhɑːtmɑː gɑːṃdhɪː əʊrə vɪnobɑː bhɑːvɛ jəɪsɛ svətəṃtrətɑː sɛnɑːnɪː rɑːṣṭrɪːyə ɛkətɑː kɪː dṛṣṭɪ sɛ rɑːṣṭrəbhɑːṣɑː kɛ ruːpə mɛṃ hɪṃdɪː əʊrə rɑːṣṭrɪːyə lɪpɪ kɛ ruːpə mɛṃ dɛvənɑːgərɪː lɪpɪ ko sthɑːpɪtə kərənɛ kɛ lɪɛ prəyɑːsərətə thɛ. Yəhɑːm̐ təkə kɪ śəhɪːdɛ ɑːzəmə bhəgətə sɪṃhə nɛ bhɪː əpənɪː mɑːtṛbhɑːṣɑː pəṃjɑːbɪː kɛ lɪɛ gurumukhɪː kɛ bəjɑːɛ vəɪjñɑːnɪkətɑː kɛ cələtɛ dɛvənɑːgərɪː ko əpənɑːnɛ kɪː bɑːtə kəhɪː thɪː. Unəkɑː prəyɑːsə thɑː kɪ dɛśə kɛ jɪnə hɪssoṃ mɛṃ dɛnəvɑːgərɪː prəcəlɪtə nəhɪːṃ həɪṃ vəhɑːm̐ bhɪː jənə-jənə təkə dɛvənɑːgərɪː lɪpɪ pəhuṃcɑːɪː jɑːɛ. Ɪsəlɪɛ məhɑːtmɑː gɑːṃdhɪː və vɪnobɑː bhɑːvɛ dvɑːrɑː hɪṃdɪː kɛ sɑːthə-sɑːthə dɛvənɑːgərɪː lɪpɪ kɛ lɪɛ ənɛkə səṃsthɑːɛm̐ khər̤ɪː kɪː thɪː.

What are your thoughts on this scheme?
अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः अम्‌ अन्‌
ə ɑː   ɪ iː u uː ṛ  ṝ   ɛ əɪ o əu æ ɔ əḥ əm ən

अं आं इं ईं उं ऊं एं ऐं ओं औं  ॐ  अँ आँ इँ ईँ उँ ऊँ एँ 
ə̇ ɑ̇ː  ɪ̈  ïː u̇ u̇ː ɛ̇ əɪ̈ ȯː əu̇ oːm ə̆̇ ɑ̆̇ː ɪ̆̇ ĭ̇ː ŭ̇ ŭ̇ː ɛ̆̇

क ख ग घ ङ
kə khə gə ghə ṅə

च छ ज झ ञ
chə chhə jə jhə ñə

ट ठ ड ढ ण 
ṭə ṭhə ḍə ḍhə ṇə
 
त थ द ध न
tə thə dhə dhə nə

प फ ब भ म
pə phə bə bhə mə

य र ल ळ व ह
yə ɾə lə ḷə və hə

श ष स क्ष ज्ञ त्र श्र
shə ṣə sə kṣə jñə ṭrə shɾə

क़ ख़ ग़ ज़ ड़ ढ़ फ़ ऱ ऴ
ḳə ḳhə g̣ə j̣ə d̤ə d̤hə f̣ə ṛə ḷə

**Comment by virtualvinodh** [comment]
I'll probably add an option that will enable people to upload their own mappings and then do the conversion.
