### ISSUE TITLE
Improvements to Telugu script

### ISSUE THREAD

**Issue by Geochiraltax** [virtualvinodh/aksharamukha#160]
Many old Telugu texts use a special character to denote what's now denoted by **న్** (IAST: **n** ). For reference, here are some examples (underlined by me in red) from ఆంధ్రశాబ్దచింతామణి (Āndhraśabdacintāmaṇi, by Nannaya Bhaṭṭāraka) 

![ప్రోవుతన్, పోషించుతన్](https://user-images.githubusercontent.com/19777432/134814887-ea6085e3-1b2c-401c-86ba-2e4216b01b65.png)

The words are actually ప్రోవుతన్, పోషించుతన్ [IAST: provutan, poṣiñcutan] 

Currently, Aksharamukha doesn't seem to support this character.

Many pre-modern and modern Telugu texts still use the letters ౘ and ౙ (referred to as _Brown Cha_ and _Brown Ja_ respectively, after their creator, C.P. Brown, who put the Telugu numeral ౨ (2) on top of the letters to denote '2nd ca and ja'). They don't have a corresponding character in IAST as far as I know, but it's pronounced somewhat like 'tsa' and 'dza/za'. In fact many common Telugu words use these letters and people actively use them in social media as well, as can be seen in the name of this Quora space (I've circled _Brown Ja_ in red):

![Name of the Quora space: మేలిమి తెలుఁగు ౙగిల (IAST: _melimi tĕlun̆gu dzagila_ ) ](https://user-images.githubusercontent.com/19777432/134817445-78a8933f-21b5-4c9e-8cb8-e9fbc69a8b61.png)

Now, as I mentioned about _Brown Cha_ and _Brown Ja_ , I'd also like to mention another point about Telugu orthography. Recently, I read this Telugu script page on Aksharamukha and regarding this section here, I have a few doubts:

![image](https://user-images.githubusercontent.com/19777432/134818066-b08fd118-7251-499b-8f05-0a8d8d8eddca.png)

First of all, I'd like to point out, that even though you've pointed out some grammar texts using small underline to denote some sounds, it is actually a common practice in Telugu texts to use underlines with the same purpose as in Devanagari, i.e., to denote depression in tone while reciting Sanskrit mantras, for instance, as shown in this Wikipedia image:

![image](https://user-images.githubusercontent.com/19777432/134818286-79406691-8b87-4b92-a9a3-958363fdcbf4.png)

or, in this Telugu text (Rudra namakam)

![image](https://user-images.githubusercontent.com/19777432/134818381-f1b4c953-4812-46be-a601-fe84659716d6.png)

You can notice how underline denotes tone depression and a vertical bar above a letter denotes an elevation in tone (however, in the image I've attached, elevation has been denoted by using an apostrophe instead of an actual vertical bar over the letter). 

This picture shows text (mantrapuṣpaṃ) using proper vertical bars above letters to denote tonal elevation as well:

![image](https://user-images.githubusercontent.com/19777432/134818858-5799d2f3-8dbe-47b6-aa35-fcaac48d523a.png)

Also, regarding the equivalent letters here:

![image](https://user-images.githubusercontent.com/19777432/134818547-619fa904-61c6-4e06-8c37-298b1ded3669.png)

I propose that the 'underlined letters' along with the above 'equivalent letters' would better be using the Brown system (placing numeral ౨ above the letter, like ౘ and ౙ) in place of underlines and dots to avoid confusion and for better precision.

**Comment by virtualvinodh** [comment]
Unfortunately, there is no equivalent Unicode character for combining number 2 in Telugu.

We have recently proposed the Telugu Nakara Pollu and Telugu Nukta for encoding and it has been accepted and have already been published in Unicode. Once fonts get updated, I can use them.

https://www.unicode.org/L2/L2020/20085-telugu-nukta.pdf
https://www.unicode.org/L2/L2020/20084r-telugu-nakaara-pollu.pdf

https://unicode.org/charts/PDF/U0C00.pdf

It might take a year or two until we have proper support for these new characters.

V
