### ISSUE TITLE
Add variants of Nagari Script

### ISSUE THREAD

**Issue by lalitaalaalitah** [virtualvinodh/aksharamukha#162]
There are a few scripts which are found in Manuscripts abundantly as Nandi Nagari[https://en.wikipedia.org/wiki/Nandinagari], Sylheti Nagari[https://en.wikipedia.org/wiki/Sylheti_Nagri], etc. which  if needed will allow manuscript-readers, researchers to practice these scripts on know texts.
I request you to add, if compatible fonts  are easily available.

**Comment by Geochiraltax** [comment]
Sylheti script [Syloti Nagari] is already supported by Aksharamukha.

http://aksharamukha.appspot.com/describe/SylotiNagri
