### ISSUE TITLE
Add tickable option to use Devanagari Accent marks with Brahmi

### ISSUE THREAD

**Issue by UltraGamerine** [virtualvinodh/aksharamukha#163]
A suggestion to add a tickable option to use Devanagari vedic Accent marks with Brahmi

I know it creates issues in some places, where they combine and create unviewable syllables.
It seems to be working fine with Google's noto sans brahmi

I have found it very usefull and easier to read like such, instead of the unicode up & down arrows for accent in brahmi.

Like an image I created here, I had to manually add the svarita and anudata, so such an option might come handy.

![20211015_153544](https://user-images.githubusercontent.com/64453040/138830933-43c55d56-036b-4ba1-aa1d-5a0f37229017.jpg)

Edit - I know there are some spacing issues with Brahmi, so these might not look as good with it.
In the image I used spaces between the glyphs and double space between the words for better readability. 
So I think adding custom spacing scheme might be a little extensive for this little option.
But anyhow, this option, even without extra spacing, might be very useful

**Comment by virtualvinodh** [comment]
There aren't any good fonts that support Svaras on Brahmi. Even if they do, they will be anachronistic.

I'm closing this for now. 

V
