### ISSUE TITLE
Extension of Urdu/Introduction of Arabi Malayalam

### ISSUE THREAD

**Issue by Geochiraltax** [virtualvinodh/aksharamukha#166]
Is there a possibility to extend existing Urdu script to support the now-missing nasal characters of _ṅa_ , _ña_ , _ṇa_ ; separate characters for _śa_ and _ṣa_ ; characters for south-Indic consonants _l̤a_ , _ḻa_ , _ṟa_ , _ṉa_ ?

Or even better, provide support for [Arabi Malayalam ](https://en.wikipedia.org/wiki/Arabi_Malayalam_script)as a new option for Urdu that can be toggled? Because apparently, Arabi Malayalam has all characters that support full set of nasals, separate characters for _śa_ and _ṣa_ and also south-Indic consonants and even short vowels _ĕ_ and _ŏ_ .

**Comment by virtualvinodh** [comment]
Arabi Malayalam, Syriac Malayalam, and Arabic-Tamil are on my to-do list!

I will add them soon

**Comment by virtualvinodh** [comment]
Closing this, as I already have an issue for this.

https://github.com/virtualvinodh/aksharamukha/issues/64
