### ISSUE TITLE
Scroll option

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#167]
when plain text is copied on the input side, the cursor is at the bottom / last lines.

post-conversion, when output is displayed, the cursor is on top lines/page. 

there is a scroll/arrow on output side to go up / down. 

but there is NO such 'short cut' to go to top lines / page on the input side. 

possible to have an option similar to the output side?

Better still, one single scroll up/down arrow that moves BOTH input & output at the same time, aligning the corresponding input and output lines ( too much to as for !)

**Comment by virtualvinodh** [comment]
The input text box has its own scroll bar. I'm not implement this for now.
