### ISSUE TITLE
OCR hrasva vowel symbols

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#168]
The hrasva e & o dev vowel symbols get converted to deerga symbols while OCRing:

eg:
तॆन्‌  becomes तेन्‌
तॊल्‌  becomes तोल्‌
नॆञ्जमे  becomes नेञ्जमे 

and so on. 

The OCR engine needs correction.

**Comment by virtualvinodh** [comment]
The OCR engine is provided by Tesseract.

https://github.com/tesseract-ocr/tesseract

That is where you need to raise the issue.

V
