### ISSUE TITLE
Conversion from Devanagari pdf to Tamil conversion

### ISSUE THREAD

**Issue by srinivasangopinath** [virtualvinodh/aksharamukha#170]
I have 10 Rig veda mandala pdf download. Tried to convert it to tamil and it is consistently stuck in 24th page.. Please advise

**Comment by virtualvinodh** [comment]
@srinivasangopinath How big are the files?

If they're too big, I library might be struggling to perform the OCR.

Perhaps, try uploading smaller chunks?

V

**Comment by virtualvinodh** [comment]
As there is not response, I am closing this issue.
