### ISSUE TITLE
Misplaced Anusvara in Galik

### ISSUE THREAD

**Issue by Geochiraltax** [virtualvinodh/aksharamukha#171]
I've noticed this:

![image](https://user-images.githubusercontent.com/19777432/149269849-e8672934-4f3f-4efe-8298-1ceb9ca48646.png)

![image](https://user-images.githubusercontent.com/19777432/149272087-b823b5a4-d539-47ec-aa63-0bd9fdf745be.png)

I can't really figure out a pattern here but it seems like when there's a hrasvaakshara (non-conjunct) in the beginning and one anusvara elsewhere in the word, Aksharamukha puts the anusvara on the first letter of the word. 

![image](https://user-images.githubusercontent.com/19777432/149272623-c209d9f7-8fad-4ca5-9391-baa516ae04eb.png)

**Comment by virtualvinodh** [comment]
That looks alright.

AFAIK Galik places Anusvara before the consonant (which Phags Pa also does)

V
