### ISSUE TITLE
Urdu transliteration problems

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#172]
Observe the following |-separated transliterations (with the final devanAgarI being off)-

```
ab|اب|ाب
ib इव|اب|ाب
ibtidā|ابتدا|ाبتदा
ḵẖirāj|خراج|خराج

```

etc..

More - 

```
آباد|आबाد 
اباحت|ाबाःت
अबाधा|ابادها|ाबाدهा
```

**Comment by virtualvinodh** [comment]
@vvasuki 

You would have to mark "Short vowels not shown". I think the converter is expecting a fully vocalized Urdu.

![image](https://user-images.githubusercontent.com/1050975/156628813-0236660f-e829-4363-97e9-9e1cb7ba0479.png)

You can get the consonantal skeleton rendered in Devanagari. Without lexical lookup (or a machine learning model), it is not possible to guess the missing short vowels

V

**Comment by vvasuki** [comment]
I see. 

Why is ابادها transliterated to अबादهअ instead of अबाधा?

**Comment by virtualvinodh** [comment]
The word ابادها uses the wrong letter for aspiration. It should use heh doachashmee U+06BE but instead used U+0647 heh.

V
