### ISSUE TITLE
The Bangla compounds using য instead of য় for Devanagari य, the behaviour of Anuswar, and the B/ W in Sanskrit

### ISSUE THREAD

**Issue by milindchakraborty** [virtualvinodh/aksharamukha#173]
भयभीत। संयुक्त। युक्ताक्षर। युवक। आर्य। गृहयुद्ध। दृढ। आडम्बर।
![text (1)](https://user-images.githubusercontent.com/64827324/153932159-0fff09dc-c7b8-4c47-9767-74e9c92b4401.png)

Any elemental word starting with य, ड and ढ in Sanskrit, uses য, ড, ঢ in Bangla.
युद्ध - যুদ্ধ
यम - যম
डमरु - ডমরু
ढोलक - ঢোলক

In the middle/ end positions, in consonant clusters they stay, য, ড, ঢ
आर्य - আর্য
दुर्योग - দুর্যোগ
धन्य - ধন্য
जाड्य - জাড‍্য
चण्डी - চণ্ডী
धनाढ्य - ধনাঢ্য
ओड्रक - ওড্রক

But in other case of non-initial positions they become য়, ড়, ঢ়
दृढ - দৃঢ়
आषाढ - আষাঢ়
भय - ভয়
आयुध - আয়ুধ
आयुर्वेद - আয়ুর্বেদ
सहायता - সহায়তা
आडम्बर - আড়ম্বর
ओडिशा - ওড়িশা

But the catch is, this only apply to elemental words without prefixes or suffixes and compounds; the य, ड, ढ in the initial position of an elemental word will be য, ড, ঢ...

संयुक्त = सम् + युक्त = সম্ + যুক্ত = সংযুক্ত
अयोग्य = अ + योग्य = অ + যোগ্য = অযোগ্য
निर्भरयोग्य = निर्भर + योग्य = নির্ভর + যোগ্য = নির্ভরযোগ্য
गृहयुद्ध = गृह + युद्ध = গৃহ + যুদ্ধ = গৃহযুদ্ধ
लक्ष्मीडांगा = लक्ष्मी + डांगा = লক্ষ্মী + ডাঙা = লক্ষ্মীডাঙা
अढेल = अ + ढेल = অ + ঢেল = অঢেল

Apparently there are exceptions
प्रयोग = প্রয়োগ
But प्रयुक्त = প্রযুক্ত
नियोग = নিয়োগ
But नियुक्त = নিযুক্ত
प्रयोजन = প্রয়োজন not প্রযোজন, निष्प्रयोजन = নিষ্প্রয়োজন.
Although, सुयोग, उपयोग are সুযোগ, উপযোগ.

So there must be a rigorous check by breaking the words. I don't even think this can be rule-based with 100% accuracy.

Also Anuswar acts differently
If it's by samas or sandhi, or not in-front of वर्गीय consonants, or in-front of complex consonant clusters

Like
संगीत = सम् + गीत = সংগীত
संख्या = সংখ্যা
पंक्ति = পংক্তি
अंश = অংশ
संयुक्त = সংযুক্ত
अपभ्रंश = অপভ্রংশ
संसार = সংসার
किंवा = কিংবা

But in front of वर्गीय consanants... It takes the nasal character form ঙ, ঞ, ণ, ন, ম
अंक = অঙ্ক
अंग = অঙ্গ
पंख = পঙ্খ
पंच = পঞ্চ
वांछित = বাঞ্ছিত
कंठ = কণ্ঠ
भंड =  ভণ্ড
दंत  = দন্ত
क्रंदन = ক্রন্দন
संबंध = সম্বন্ধ
संमति = সম্মতি
Etc.

The ending म् in Sanskrit is usually replaced by anuswar, but at the end of a line or before '।' it is rendered as ম্...
सत्यम् शिवम् सुंदरम्।
সত‍্যং শিবং সুন্দরম্।

If the म् is followed by च, it is often rendered as ञ्च and the words get joined, but that's not universal.
बुद्धिं च प्रचोदयात्
বুদ্ধিঞ্চ প্রচোদয়াৎ or বুদ্ধিং চ প্রচোদয়াৎ.

The wa conjuncts are differentiated from the ba conjuncts in standard spelling, (not everyone follows but Bangla Academy prescribes)
স্বত্ব - स्वत्व
ক্বাথ - क्वाथ
সাত্বিক - सात्विक
উদ্‌বোধন - उद्बोधन so not উদ্বোধন
উদ্‌বুদ্ধ - उद्बुद्ध so not উদ্বুদ্ধ
বাল্‌ব - बल्ब so not বাল্ব

This obviously doesn't apply to म् + ब (Sanskrit law)
सम्बन्ध - সম্বন্ধ
गम्बुज - গম্বুজ
कम्बल - কম্বল

Note: While talking about sandhi words and use of separate hasanta, words like
वाग्धारा = वाक् + धारा = বাগ্‌ধারা not বাগ্ধারা
वाक्युद्ध = वाक् + युद्ध = বাক্‌যুদ্ধ not বাক‍্যুদ্ধ
ऋग्वेद = ऋक् + वेद = ঋগ্‌বেদ/ ঋক্‌বেদ not ঋগ্বেদ
Etc.

Ramakrishna Mission (Udbodhana Karyalaya) way of  Sanskrit transcription uses ৰ for writing b in Sanskrit as opposed to ব for w. 

যা দেবী সর্বভূতেষু ৰ‌ুদ্ধি রূপেণ সংস্থিতা।
নমস্তস্যৈ॥ নমস্তস্যৈ॥ নমস্তস্যৈ॥ নমো নমঃ॥
या देवी सर्वभूतेषु बुद्धि रूपेण संस्थिता।
नमस्तस्यै॥ नमस्तस्यै॥ नमस्तस्यै॥ नमो नमः॥

But there are some quirks,
बु is ৰ‌ু not ৰু
बू is ৰ‌ূ not ৰূ

The compounds are, ম্‍ৰ/ ম্‌ৰ in সম্‍ৰন্ধ/ সম্‌ৰন্ধ (संबंध) not সম্ৰন্ধ, ब्रूहि will be ৰ‍্ৰূহি, ब्य will be ৰ‍্য, र्ब will be ৰ্ৰ, ब्ब will be ৰ্‌ৰ (honestly should look like ব্ব, but I don't know if that's doable), ब्ल will be ৰ‍্ল (honestly should look like ব্ল but is that doable in Unicode) ब्ध will be ৰ্‌ধ (should actually look like ব্ধ), ब्ज should be ৰ্‌জ (should actually look like ব্জ) etc. It behaves like ব in conjuncts basically.

![20220224_193116](https://user-images.githubusercontent.com/64827324/155539300-915b0efe-1662-4e21-a9ce-15fd46570b98.jpg)
![20220224_193144](https://user-images.githubusercontent.com/64827324/155539311-4bcedfb6-b21d-48f8-90e2-106349e6d8c8.jpg)
![20220224_193241](https://user-images.githubusercontent.com/64827324/155539319-5f0346cf-599e-4fa6-8e71-b68199e16e67.jpg)
![20220224_193404](https://user-images.githubusercontent.com/64827324/155539322-b4edc927-456f-4467-a476-1835427a923d.jpg)

**Comment by virtualvinodh** [comment]
That's a lot of useful information. 

I cannot implement that requires Sandhi-splitting or any sort of lexical analysis. But I can sure I can implement the other relevant parts.

For the conjuncts, we could fork Noto Sans Bengali and create the required forms. But the question would be is that really worth the effort (how many will actually use it?)

V

**Comment by milindchakraborty** [comment]
> That's a lot of useful information.
> 
> I cannot implement that requires Sandhi-splitting or any sort of lexical analysis. But I can sure I can implement the other relevant parts.
> 
> For the conjuncts, we could fork Noto Sans Bengali and create the required forms. But the question would be is that really worth the effort (how many will actually use it?)
> 

We should atleast include the case of non-cluster and non-initial positions of য, ড, ঢ becoming য়, ড়, ঢ়.
(Also an option if someone doesn't want to do that)

Also there should be an option to convert the anuswar in front of वर्गीय consanants ({क, ख, ग, घ, ङ}, {च, छ, ज, झ, ञ}, {ट, ठ, ड, ढ, ड़, ढ़, ण}, {त, थ, द, ध, न}, {प, फ, ब, भ, म}) into the corresponding nasal ঙ্, ঞ্, ণ্, ন্, ম্. Universally using anuswar is incorrect in Bangla, Assamese and Odia.

> पंक्ति = পঙ্ক্তি [usually written as : পঙ্‌ক্তি or পংক্তি]
> अंक = অঙ্ক
> अंग = অঙ্গ
> पंख = পঙ্খ
> पंच = পঞ্চ
> वांछित = বাঞ্ছিত
> कंठ = কণ্ঠ
> भंड = ভণ্ড
> दंत = দন্ত
> क्रंदन = ক্রন্দন
> संबंध = সম্বন্ধ
> संमति = সম্মতি

Note: किंवा is কিংবা, since it has व/w; संबंध is সম্বন্ধ, since it has ब/b.

Also, following the modern standard spelling norms, separating ्ब, ्व is necessary...

> স্বত্ব - स्वत्व
> ক্বাথ - क्वाथ
> সাত্বিক - सात्विक
> উদ্‌বোধন - उद्बोधन so not উদ্বোধন
> উদ্‌বুদ্ধ - उद्बुद्ध so not উদ্বুদ্ধ
> বাল্‌ব - बल्ब so not বাল্ব

Note: म्ब will be ম্ব only.

This should also be given as an option when the user wants to render ্‌ব as ্ব.

The Ramakrishna Mission way of differentiating w and b in Sanskrit, should definitely be included, I guess. As an option.
ৰ for ब/b, ব for व/w.

Just makes sure.
बु is ৰ‌ু not ৰু
बू is ৰ‌ূ not ৰূ

In case of conjuncts, I noticed, they always show the ৰ clusters separated by halanta/virama. Which actually makes sense.
Except:
र्ब - ৰ্ৰ
ब्र - ৰ‍্ৰ (like : ৰ‍্ৰূহি)
ब्य - ‍ৰ‍্য

Apart from these, all others
संबंध/सम्बन्ध - সম্‌ৰন্ধ
ब्ल - ৰ‍্ল
ब्ब - ৰ্‌ৰ
ब्ध - ৰ্‌ধ
ब्ज - ৰ্‌জ
i.e. ्ब = ্[ZWNJ]ৰ, ब्[x] = ৰ্[ZWNJ][x]

This isn't super necessary, but given we go this far for Sanskrit to Bangla conversion, why not also do the terminal म् thingy? As an option.

> The ending म् in Sanskrit is usually replaced by anuswar, but at the end of a line or before '।' it is rendered as ম্...
> सत्यम् शिवम् सुंदरम्।
> সত‍্যং শিবং সুন্দরম্।
>
> If the म् is followed by च, it is often rendered as ञ्च and the words get joined, but that's not universal. This should be an option too.
> बुद्धिं च प्रचोदयात्
>বুদ্ধিঞ্চ প্রচোদয়াৎ or বুদ্ধিং চ প্রচোদয়াৎ.

**Comment by virtualvinodh** [comment]
This has been implemented. It should be available in about two weeks when I push the next big update.

@milindchakraborty Thanks a lot for this. I learnt a lot about Bengali orthography!

> This isn't super necessary, but given we go this far for Sanskrit to Bangla conversion, why not also do the terminal म् thingy? As an option.

I am holding this for now. At this point, we are entering the realm of fixing Sanskrit grammar instead of orthography. We should let Google /Microsoft handle this :)

I am closing this. If you have any other suggestions, please do open a new issue.

**Comment by virtualvinodh** [comment]
@milindchakraborty  Also please look at the latest post on https://github.com/virtualvinodh/aksharamukha/issues/65

**Comment by virtualvinodh** [comment]
@milindchakraborty 

I'm writing a proposal to encode this alternate BA (or at least clarify a mechanism to render it properly). Can you please share the sources for the images that you shared? I would like to use them in my proposal.

Cheers,

Vinodh

**Comment by milindchakraborty** [comment]
> @milindchakraborty
> 
> I'm writing a proposal to encode this alternate BA (or at least clarify a mechanism to render it properly). Can you please share the sources for the images that you shared? I would like to use them in my proposal.
> 
> Cheers,
> 
> Vinodh

I just saw your proposal. I am really sorry about not being able to reach out earlier. Lot of mishaps happening parallelly. The proposal is great.

https://www.unicode.org/L2/L2022/22268r-bengali-alternate-ba.pdf

I would have mentioned the name of sources, but wonder if that would be necessary since you have already sent the proposal.
The first two pictures are from শ্রীমদ্ভগবদ্‌গীতা (Srimad Bhagwad Gita) by স্বামী জগদীশ্বরানন্দ and স্বামী জগদানন্দ and the last two pictures are from শ্রীশ্রীচণ্ডী (Sri Sri Chandi - Devi Mahatmyam) also by স্বামী জগদীশ্বরানন্দ. Both books are published from উদ্‌বোধন কার্যালয় (Udbodhan Karyalay - Ramakrishna Mission).

I saw that Srinidhi also proposed in support.
https://www.unicode.org/L2/L2022/22278-bengali-alt-ba-pali.pdf

Please let me know about updates.

Regards,

Milind Chakraborty
