### ISSUE TITLE
Bug: For Gurmukhi dependent long-vowel 'u', use tippi instead of bindi

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#175]
Example:
|Devanagari|Current|Expected|
|---|---|---|
| लूंबड़ी | ਲੂਂਬੜੀ | [ਲੂੰਬੜੀ](https://en.wiktionary.org/wiki/ਲੂੰਬੜੀ) |
| मूंह | ਮੂਂਹ | [ਮੂੰਹ](https://en.wiktionary.org/wiki/ਮੂੰਹ) |

For the given Hindi references, it can be seen that in Punjabi, it should have used tippi as anusvara instead of bindi (for the syllable with long-vowel 'u'). This seems to be an exception in Gur'mukhi for the diacritic 'uu'.

Source: [Gurmukhi Nasalization - Wikipedia](https://en.wikipedia.org/wiki/Gurmukhi#Nasalisation)

**Comment by virtualvinodh** [comment]
Fixed. Will be updated in the next update
