### ISSUE TITLE
Option to enable old/alternative glyphs for Dogra

### ISSUE THREAD

**Issue by nik9hil** [virtualvinodh/aksharamukha#179]
There are alternative & old forms for glyphs present in Noto Serif Dogra font package. It would be useful if we could provide option to use some of them in the converter. 

Image 1: Vowels & Consonants

<img width="542" alt="image" src="https://user-images.githubusercontent.com/32241740/160239119-2a1e143a-a9ac-4ee2-b6d7-c37290ec403b.png">

Image 2: Vowel Markers
<img width="322" alt="image" src="https://user-images.githubusercontent.com/32241740/160239141-06ba1424-aafd-4936-8d33-c0f1aa6cff44.png">

**Comment by virtualvinodh** [comment]
Fixed. Will be updated in the new version
