### ISSUE TITLE
Missing characters?

### ISSUE THREAD

**Issue by Naresh-Keerthi** [virtualvinodh/aksharamukha#18]
Hi,
Thanks for developing this wonderful tool Aksharamukha. I have two issues to point out – 
1.	The Harvard-Kyoto scheme is designed primarily to transliterate material that uses devanāgari, so it doesn’t have symbols corresponding to the Dravidian ற, ன and ழ  sounds. Your app works fine even for transliterating material in Kannada or Tamil, but I do not know if there is a H-K equivalent for these phonemes. Can you please help?

2.	A connected issue – when I use this tool to transliterate Old Kannada, the following two graphemes appear to be missing - ಱ  =  ṟ  | ற and ೞ  = ḻ | ழ. I do not know if there is some easy way to incorporate these characters with an H-K convention for them; it would be a great improvement. Right now, I enter the text with the conventional r and ḷ (ರ and ಳ respectively), convert it using aksharamukha, and later manually replace the ಱ and ೞ characters.

**Comment by virtualvinodh** [comment]
Hi Naresh,

Have a look at this:

http://aksharamukha.appspot.com/#/roman

Try changing the script to Tamil or Kannada at the top-right corner. I have added the necessary extensions to HK in order to support the South Indian characters.

V

**Comment by Naresh-Keerthi** [comment]
Hello Vinodh,

Thanks for the prompt response. This is excellent.

Warm Regards,
Naresh
