### ISSUE TITLE
copy button on top

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#183]
Copy button below the transliteration result is placed in the bottom. It should be placed in the top as well. 

Reason:

- "Paste some text, transliterate it, copy it" is a common usage sequence.
- The copy button is pushed down if the resulting transliterated text is large, forcing one to scroll. 
- Scrolling is tedious.

**Comment by virtualvinodh** [comment]
I have implemented this. Will be fixed in the next update in a week or two.
