### ISSUE TITLE
Handling Itrans ## 

### ISSUE THREAD

**Issue by vpysb** [virtualvinodh/aksharamukha#195]
This seems to work on the website such as https://sanskritdocuments.org/doc_veda/chaturvedAdyamantrAH.html which uses aksharamukha script basis the itx file https://sanskritdocuments.org/doc_veda/chaturvedAdyamantrAH.itx as its source.

The same itx file does not seem to process right with the python package with itrans to deva when ## is present in the file. ## is expected to skip transliteration.

Is this file to be pre-processed for ## before transliteration?

**Comment by virtualvinodh** [comment]
I think I fixed it.

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/de14a84a-747f-4c8f-a8c5-b75835565331)

It should be fixed in the next version of the package.
