### ISSUE TITLE
manipravALa/ tamil failure with ஞ் சொ

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#198]
प्रभावத்தையுஞ் சொல்லுகைக்காகவத்தனை. இப்படி (from [here](https://srivaishnavan.com/publications/meghamala/rahasysa-granthas/srimad-rahasya-traya-saram-content/%e0%a4%b6%e0%a5%8d%e0%a4%b0%e0%a5%80%e0%a4%ae%e0%a4%a6%e0%a5%8d%e0%a4%b0%e0%a4%b9%e0%a4%b8%e0%a5%8d%e0%a4%af%e0%a4%a4%e0%a5%8d%e0%a4%b0%e0%a4%af%e0%a4%b8%e0%a4%be%e0%a4%b0%e0%a5%87-%e0%a4%85%e0%a4%aa/) ) to devanAgarI yields प्रभावत्तैयुञ् जॊल्लुगैक्कागवत्तनै. इप्पडि

Should have been चॊल्लुगैक्…

**Comment by virtualvinodh** [comment]
ச followed by ஞ் usually becomes ज.

I would certainly read it as   प्रभावत्तैयुञ् जॊल्लुगैक्कागवत्तनै.

In any case, if you want something specific to Manipravala try this.

http://www.manipravala.com/wp/manipravala-editor/

http://www.manipravala.com/wp/how-to-use-manippavalam/

V
