### ISSUE TITLE
mixed script maNipravALa failure वैषम्यम्पोले 

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#199]
([स्रोतः](https://srivaishnavan.com/publications/meghamala/rahasysa-granthas/srimad-rahasya-traya-saram-content/%e0%a4%b6%e0%a5%8d%e0%a4%b0%e0%a5%80%e0%a4%ae%e0%a4%a6%e0%a5%8d%e0%a4%b0%e0%a4%b9%e0%a4%b8%e0%a5%8d%e0%a4%af%e0%a4%a4%e0%a5%8d%e0%a4%b0%e0%a4%af%e0%a4%b8%e0%a4%be%e0%a4%b0%e0%a5%87-%e0%a4%85%e0%a4%aa/)) वैषम्यம்போலே should yield वैषम्यम्पोले , but produces वैषम्यम्बोले

एवं हि - तथैव - मोक्षம்பெறுகைக்குக்।  

~~ம்பெ should be म्पो even without mixed script consideration, right?~~ (एम्बॆरुमान् इत्य् उदाहरणं सूचितम्। )

**Comment by virtualvinodh** [comment]
Again, please see my previous comment. 

I would pretty much read it as वैषम्यम्बोले, nasalized /p/ usually becomes /b/ unless it's a loan word.

V
