### ISSUE TITLE
Errors in Noto Sans Newa

### ISSUE THREAD

**Issue by Suwarn** [virtualvinodh/aksharamukha#2]
First, let me thank you Vinodh for developing a Noto Sans Newa font. 
But I shall appreciate it very much if you can correct some errors. 
1) The shape does not look at all like Nepal Lipi letters. 
2) The size is smaller than the normal for example when entered into SNS, the letters appear unreadably small. 
3) Though you have correctly used the term Nepal Bhasa correctly, the fonts are named as Noto Sans Newa. It should be corrected as Noto Sans Nepal Lipi.
4) There are a number of errors in compound letters both shape and size while the mark for the letter  'r' doesn't appear correctly. 
5) If it is useful, please have a look at the Nepal Lipi syllabary, we Nepalese use:  https://vajracharya.files.wordpress.com/2015/11/nepal-lipi-an-introduction-to-how-to-read-and-write.pdf
6) Please visit https://nepal-lipi.webgarden.com for our website posts and online magazines we have so far published in promoting Nepal Lipi of the Nepal Bhasa, the original languaage of Nepal.
7) If there is anything I can do to help you, please let me know. 
- Suwarn Vajracharya
   suwan_vj@hotmail.com

**Comment by virtualvinodh** [comment]
Dear Suwarn,

I haven't developed the Noto Sans Newa font. It was done by google. You may want to report the issue under here:

https://github.com/googlei18n/noto-fonts/issues

There are already some issues logged into for the Newa font. You may want to see it as well.

https://github.com/googlei18n/noto-fonts/issues?q=is%3Aissue+is%3Aopen+newa+label%3AScript-Newa

V
