### ISSUE TITLE
Using diaeresis sign to indicate hiatus in ISO/IAST

### ISSUE THREAD

**Issue by sridatta1** [virtualvinodh/aksharamukha#20]
Transferring from slack group  and filing here for tracking issues
here http://aksharamukha.appspot.com/#/roman अइ अउ are generally written as aï and aü which commonly occur in Prakrit, Apabhraṃśa, NIA etc. 
e.g. वट्टइ, कइवच्छलेण, जाणइ etc. are generally transliterated as vaṭṭaï, kaïvacchaleṇa, Jāṇaï. And पउम, वड्ढउ, फुरउ as paüma, vaḍḍhaï, phuraü etc. All of these are Prakrit words. They also rarely occur in sanskrit in the words प्रउग, तितउ. See http://gretil.sub.uni-goettingen.de/gretil/2_prakrt/halsatsu.htm 
http://showcases.exist-db.org/exist/apps/sarit-pm/works/pravarasena-setubandha.xml?view=page

And ISO 15919 suggests colon for vowel hiatus like pra:uga

**Comment by virtualvinodh** [comment]
Fixed
