### ISSUE TITLE
Remove apostrophe

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#200]
while transcribing dev to tam, apostrophe is used for both ऋ, ॠ, ऌ, ॡ ( ருʼ, ரூʼ, லுʼ, லூʼ)  
kRRishNA -> कृश्णा -> க்ருʼஶ்ணா

apostrophe in ருʼ, ரூʼ, லுʼ, லூʼ is to differentiate रु,रू, लु, लू  from ऋ, ॠ, ऌ, ॡ. Those who know the difference can retain it. 

as well as anusvara j~nAnAnandamayaM devaM -> ज्ञानानन्दमयं देवं -> ஜ்ஞானானந்த₃மயம்ʼ தே₃வம்ʼ

Tamil does not use anusvara, hence devaM should be treated as devam, ie without anuavara.  
li~Ngam -> लिङ्गम् -> லிங்க₃ம்
li~NgaM -> लिङ्गं -> லிங்க₃ம்ʼ

liMga -> लिंग -> லிங்க₃  - this is ok.
li~Nga -> लिङ्ग -> லிங்க₃  - this is ok.

I guess other anusvaras (~N, ~n, N, n,) are getting transcribed properly, but for ம்?

Currently there is a single option to remove apostrophe.  
Can we have 2 separate options to remove apostrophe  - one for ऋ, ॠ, ऌ, ॡ and other for M?
( or treat M=m  for end word?)

**Comment by virtualvinodh** [comment]
The apostrophe is safe to ignore anyway. I don't see a need to specifically add another option. Tamil is already too crowded.

**Comment by nsesha92** [comment]
I think I didn't make it clear.

apostrophe ideally should not be ignored when it comes to ऋ, ॠ, ऌ, ॡ, to differentiate from रु,रू, लु, लू in Tamil.

However IMO, there no need to have apostrophe for M.

liNgam = liNgaM = லிங்க₃ம் (and not லிங்க₃ம்ʼ) 
mayam = mayaM = மயம் (and not மயம்ʼ)
devam = devaM = தே₃வம் (and not தே₃வம்ʼ)

etc., as this 'M' grammar rule is not there for Tamil. (all other indic languages have this rule/distinction I guess)

**Comment by nsesha92** [comment]
Current option:
Remove apostrophe  ருʼம்ʼ → ரும்
Proposed:
Remove apostrophe  ருʼ → ரு ( implies for ALL -> ருʼ, ரூʼ, லுʼ, லூʼ) for those who don't want to differentiate.

( this option is not required for Tamil, always remove Remove apostrophe  ம்ʼ → ம்)

**Comment by nsesha92** [comment]
Tamil Extended has this option:
Avoid Anusvara
സംഘം → സങ്‌ഘമ്

With this option:
li~Ngam = li~NgaM
ലിങ്‌ഗമ്‌ = ലിങ്‌ഗമ്‌

Without this option

li~Ngam = ലിങ്‌ഗമ്‌
 li~NgaM  = ലിങ്‌ഗം

Same option in Tamil to remove anusvara ' for M
