### ISSUE TITLE
Incorrect Do Chashmi He diacritic placement in Shahmukhi/Urdu

### ISSUE THREAD

**Issue by bgo-eiu** [virtualvinodh/aksharamukha#204]
If we convert ਜੱਫੀ (Gurmukhi) to Shahmukhi we get جپّی for example. The shadd should be over do chashme he, as پھ acts as a combined letter with ھ as the holder for any diacritics

**Comment by virtualvinodh** [comment]
Thanks for raising this!

I have fixed this and will push the update in a couple of days!

V

**Comment by bgo-eiu** [comment]
Thanks!
