### ISSUE TITLE
Why does Bengali Conjunct Ligature has ZWNJ in-between?

### ISSUE THREAD

**Issue by GokulNC** [virtualvinodh/aksharamukha#205]
For example, when I transliterate the word "द्बारा" (dbArA) to Bengali, it is rendered as "দ্‌বারা".
This happens even if `preserve source` is set. Is this intentional?

Although I understand that aksharamukha expects "द्वारा" (dvArA) explicitly inorder to render it properly as "দ্বারা" following _sAdhu bhAShA_ standard for Sanskrit transliteration, it would be more clear if we can transliterate _dbArA_ as দ্বারা when `preserve source` is set.

**Comment by virtualvinodh** [comment]
@GokulNC 

Thanks for highlighting this.  It was indeed slightly confusing.

I have changed this behavior.

By default udvega and udbodhana will become উদ্বেগ উদ্বোধন. If _preserve source_ is enabled, the converter will attempt to distinguish between them using the explicit Virama (as suggested by the Bangla Academy) as উদ্বেগ উদ্‌বোধন .

I will push this as well this week.

V
