### ISSUE TITLE
Issue with ṛh conversion between Gurmukhi and Devanagari

### ISSUE THREAD

**Issue by bgo-eiu** [virtualvinodh/aksharamukha#212]
Gurmukhi and Devanagari differ in that Gurmukhi has ੜ for ṛ whereas Devanagari uses ḍ+nuqta/bindi as ड़. This conversion works, but where the problem arises is that in Devanagari ṛh is written by attaching nuqta/bindi to the character for ḍh as in ढ़ but Gurmukhi represents ṛh using a conjunct of ṛ and h as ੜ੍ਹ (this has to do with Punjabi having tonal consonants where Hindustani has aspirated ones). The conversion currently produces ਢ਼ going into Gurkukhi and ड्ह going into Devanagari where we would expect to see ੜ੍ਹ and ढ़ respectively.

**Comment by virtualvinodh** [comment]
Fixed. Will push it in the next update.
