### ISSUE TITLE
Nun ghunna should only be used word finally when going to Urdu or Shahmukhi

### ISSUE THREAD

**Issue by bgo-eiu** [virtualvinodh/aksharamukha#213]
If we take the Punjabi word ਪੰਜ where there is a homorganic nasal, this should become پنج rather than پںج. If it would be preferrable to maintain some distinction between regular nun and the homorganic nasal in this position for the purpose of conversion in the reverse direction, there is a “gunna marker” diacritic available for this purpose as in پن٘ج . Note that if the gunna marker is present over nun no other diacritics should be attached to that nun.

At the end of the words, the use of nun gunna is correct as in ਨਾਂ = ناں

**Comment by virtualvinodh** [comment]
Fixed. Will push it in the next update.
