### ISSUE TITLE
IAST uses ṁ actually

### ISSUE THREAD

**Issue by sujato** [virtualvinodh/aksharamukha#217]
Aksharamukha follows the usual understanding that the IAST standard defines anusvāra as ṃ underdot. But I just was looking up the original papers today, and it turns out that they universally define anusvāra as ṁ overdot, giving good reasons for doing so.

https://discourse.suttacentral.net/t/it-seems-anusvara-was-represented-by-not-at-the-geneva-congress-of-1894/28164

What matters for Aksharamukha I guess is the system as adopted, namely ṃ, rather than the system as defined, but I thought it was an interesting discovery!

**Comment by virtualvinodh** [comment]
@sujato I'm finally looking into all the Github issues!

That's indeed an interesting find!

V
