### ISSUE TITLE
Kawi in Unicode

### ISSUE THREAD

**Issue by tgucio** [virtualvinodh/aksharamukha#218]
Kawi samples are currently encoded using Javanese code points. From https://aksharamukha.appspot.com/describe/Kawi:
> Kawi is not yet encoded in Unicode. Tantular Kawi uses the Javanese encoding to represent Kawi. If this particular font it not used, your text will appear as plain Javanese text.

As of Unicode 15.0, Kawi has assigned code points:

```
11F00..11F01  ; Kawi # Mn   [2] KAWI SIGN CANDRABINDU..KAWI SIGN ANUSVARA
11F02         ; Kawi # Lo       KAWI SIGN REPHA
11F03         ; Kawi # Mc       KAWI SIGN VISARGA
11F04..11F10  ; Kawi # Lo  [13] KAWI LETTER A..KAWI LETTER O
11F12..11F33  ; Kawi # Lo  [34] KAWI LETTER KA..KAWI LETTER JNYA
11F34..11F35  ; Kawi # Mc   [2] KAWI VOWEL SIGN AA..KAWI VOWEL SIGN ALTERNATE AA
11F36..11F3A  ; Kawi # Mn   [5] KAWI VOWEL SIGN I..KAWI VOWEL SIGN VOCALIC R
11F3E..11F3F  ; Kawi # Mc   [2] KAWI VOWEL SIGN E..KAWI VOWEL SIGN AI
11F40         ; Kawi # Mn       KAWI VOWEL SIGN EU
11F41         ; Kawi # Mc       KAWI SIGN KILLER
11F42         ; Kawi # Mn       KAWI CONJOINER
11F43..11F4F  ; Kawi # Po  [13] KAWI DANDA..KAWI PUNCTUATION CLOSING SPIRAL
11F50..11F59  ; Kawi # Nd  [10] KAWI DIGIT ZERO..KAWI DIGIT NINE
```

**Comment by sridatta1** [comment]
Noto Sans Kawi seems to be under development. If some other font is available to use under licenses and is functional. Then can be added or we have to wait for a while.
https://notofonts.github.io/#kawi

**Comment by virtualvinodh** [comment]
I'll leave this open until we get a working Kawi Unicode font

**Comment by virtualvinodh** [comment]
Done!
