### ISSUE TITLE
Roman (IAST) for Odia to be fixed

### ISSUE THREAD

**Issue by psubhashish** [virtualvinodh/aksharamukha#222]
I believe that the following list of books, taken from a [Worldcat listing](https://viaf.org/viaf/55419394/), is in Roman (IAST). I've tried all the other Roman options on Aksharamukha but this one is the closest. I've made a table to show the Roman version, current output and expected output so that it is easier to fix.

| **Title in Roman (IAST)** | **Current output in Odia** | **Expected output in Odia** |
|---------------------------|----------------------------|-----------------------------|
| anyānẏa                   | ଅନ୍ୟାନ୍ୟ୍̇ଅ  | ଅନ୍ୟାନ୍ୟ                      |
| Caṭighara                 | ଚତ୍̣ଇଘର                      | ଚଟିଘର                        |
| Pradakshiṇa               | ପ୍ରଦକ୍ସ୍ହିଣ                    | ପ୍ରଦକ୍ଷିଣ                      |
| Sīmita ei samaẏadehe      | ସମୟ୍̇ଅଦେହେ                   | ସମୟଦେହେ                     |
| Dhānaksheta               | ଧାନକ୍ସ୍ହେତ                   | ଧାନକ୍ଷେତ                     |

**Comment by virtualvinodh** [comment]
Fixed.

V

**Comment by psubhashish** [comment]
Thank you much, Vinod.
