### ISSUE TITLE
Compare with Thai Sanscript Project

### ISSUE THREAD

**Issue by virtualvinodh** [virtualvinodh/aksharamukha#23]
Improve Thai transliteration mapping by comparing to Thai Sanscrit

http://www.thai-sanscript.com/index.php/main/transliterate

V

**Comment by geethub** [comment]
Based on this link here is Alphabet transliteration.
http://www.thai-sanscript.com/index.php/main/transliterate
1-अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः
2-क ख ग घ ङ च छ ज झ ञ
3-ट ठ ड ढ ण त थ द ध न प फ ब भ म
4-य र ल ळ व ह श ष स
5-क़ ख़ ग़ ज़ ड़ ढ़ फ़ ऱ ऴ
6-अं आं इं ईं उं ऊं एं ऐं ओं औं
7-अँ आँ इँ ईँ उँ ऊँ एँ ऐँ ओँ औँ

1-อ อา อิ อี อุ อู ฤ ฤๅ เอ ไอ โอ เอา ऍ ऑ อะ
2-ก ข ค ฆ ง จ ฉ ช ฌ ญ
3-ฏ ฐ ฑ ฒ ณ ต ถ ท ธ น ป ผ พ ภ ม
4-ย ร ล ฬ ว ห ศ ษ ส
5-क़ ख़ ग़ ज़ ड़ ढ़ फ़ ऱ ऴ
6-อํ อํา อิํ อีํ อุํ อูํ เอํ ไอํ โอํ เํา
7-อัํ อัํา อิัํ อีัํ อุัํ อูัํ เอัํ ไอัํ โอัํ เัํา

**Comment by geethub** [comment]
Vowels comparison:
Devanagari / Gujarati /Thai
1-अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः ...................6 vowels based on letter "a"/ अ
1-અ આ ઇ ઈ ઉ ઊ ઋ ૠ એ ઐ ઓ ઔ ઍ ઑ અઃ ......... 9 vowels based on letter "a"/ અ 
અ આ **અિ અી અુ અૂ** ઋ ૠ એ ઐ ઓ ઔ ઍ ઑ અઃ ...13 vowels based on letter "a"/અ .......4 bold modified
3-อ อา อิ อี อุ อู ฤ ฤๅ เอ ไอ โอ เอา ऍ ऑ อะ  ............11 vowels based on letter "a"/ อ
Based on this Devanagari script may have modified these इ ई उ ऊ ए ऐ ऍ ऑ 
In Thai all the vowel sounds are based on letter a/อ / Schwa-a which is very similar to Gujanagari script
