### ISSUE TITLE
Handling Dandas in Mixed English-Devanagari text to other Indic script transliteration 

### ISSUE THREAD

**Issue by uberize** [virtualvinodh/aksharamukha#232]
My have documents that combine Devanagari and English.

e.g. take the line:

This is an instruction.
पदं ।  

If I convert this to Tamil, I want to keep the danda for the Sanskrit part. So I pick the output option "Dandas . .. → । ॥".
This is giving me:

This is an instruction।
பத³ம்ʼ ।  

In other words, the period at the end of the English instruction is also getting converted to a danda, which is unexpected and undesirable.

**Comment by virtualvinodh** [comment]
This has been fixed.

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/de27f884-68eb-4b1d-b4ee-f5d2dd62f236)
