### ISSUE TITLE
roman to devnag: apostrophy->avagraha

### ISSUE THREAD

**Issue by yakcz** [virtualvinodh/aksharamukha#234]
While trying to convert a text published in IAST into devanagari , the <'> (used to mark elided initial a-) of the source was preserved unchange in the devanagari output. It should be rendered by the so called "avagraha" sign of devanagari (U+093D), which looks:  ऽ 
Kindly implement that (perhaps best as output option)

**Comment by virtualvinodh** [comment]
It seems to work for me.

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/29959274-a4d2-4b35-ab8d-a0c3491c65aa)

Could you perhaps try again or give me the input text?

I will close the issue for now. Please feel free to reopen if you're still facing issues.
