### ISSUE TITLE
Enable kannada numerals by default

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#235]
Unlike tamil numerals, kannada numerals are widely used - in books as well as on display (bus numbers). So, the appropriate output option should be enabled by default (less labor for users.)

**Comment by nsesha92** [comment]
I had earlier suggested a Uniform (not Civil Code) option to handle numerals. 

Currently, some languages default to that language/script-specific numerals,  without an option to switch to Roman numerals. 

While others default to Roman, with an option to switch.

Suggest all languages default to that language-specific numerals with OPTION to switch to Roman -> Uniform Numeral Coding !

**Comment by nsesha92** [comment]
issue #124

**Comment by virtualvinodh** [comment]
done!

Will be pushed in the next update;

**Comment by nsesha92** [comment]
Thanks, new option to switch between kannada & roman numerals added, similar to tamil, telegu and malayalam.

But this option is not available for devanagari, gujarati, odia and other indo-aryan scripts. 

Hope it gets fixed when #124 is pushed.
