### ISSUE TITLE
On Kawi

### ISSUE THREAD

**Issue by mahalisyarifuddin** [virtualvinodh/aksharamukha#236]
Greetings.

Would you mind to update the Kawi portion to be Unicode-compliant? The script is already released in Unicode 15. On font, [Noto already has a Kawi font!](https://notofonts.github.io/kawi) It's not yet available via GF, but it's already usable.

Thank you.

[EDIT] I should have commented on #218, but yeah.

**Comment by virtualvinodh** [comment]
Done!
