### ISSUE TITLE
About some issues

### ISSUE THREAD

**Issue by Adiexr** [virtualvinodh/aksharamukha#238]
Whenever i try getting text in grantha Pandya script selected, translated from English, it doesn't get copied but it's malyalam that's getting copied on clipboard. Help sort that out...

**Comment by Adiexr** [comment]
No

**Comment by nsesha92** [comment]
I guess you need to install e-Pandya font, please see the footnote at the bottom on the output side.

"This only works with e-Pandya font and uses Malayalam codepoints to encode Grantha (Pandya) characters."

**Comment by virtualvinodh** [comment]
@nsesha92  You need this font.

https://github.com/virtualvinodh/aksharamukha-fonts/blob/main/e-Pandya.ttf
