### ISSUE TITLE
transliterating vocalic ṛ

### ISSUE THREAD

**Issue by Epigraphy** [virtualvinodh/aksharamukha#239]
I tried typing **gṛhattu** from an inscription and transliterating into Tamil as well as Tamil Extended fonts. The utility does not transliterate the vocalic ṛ correctly. Thank you for a solution.

Regards,
Palaniappan

**Comment by nsesha92** [comment]
Use Roman (IAST) as input, 
Tamil output is க்³ருஹத்து
Is this what you want?

**Comment by Epigraphy** [comment]
Thank you. But I found a workaround meanwhile.  In க்³ருஹத்து we still do not distinguish between normal r and vocalic ṛ. So, I typed gRhattu in Harvard-Kyoto and got its Tamil transliteration as க்³ருʼஹத்து. This should be enabled for ISO15919 Indic as well as IAST.

 

Regards,

Palaniappan

 

 

From: Seshadri Nadadhur ***@***.***>
Reply-To: virtualvinodh/aksharamukha ***@***.***>
Date: Monday, July 3, 2023 at 7:24 AM
To: virtualvinodh/aksharamukha ***@***.***>
Cc: Epigraphy ***@***.***>, Author ***@***.***>
Subject: Re: [virtualvinodh/aksharamukha] transliterating vocalic ṛ (Issue #239)

 

Use Roman (IAST) as input,
Tamil output is க்³ருஹத்து
Is this what you want?

**Comment by nsesha92** [comment]
They are available.
Harvard-Kyoto  Input gRhattu
output:
Tamil க்³ருʼஹத்து  (without ticking Remove apostrophe ருʼம்ʼ → ரும்)
ISO 15919 Indic gr̥hattu
IAST gṛhattu
ITRANS gR^ihattu

**Comment by virtualvinodh** [comment]
It does work.

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/6e932281-87dd-43e4-b45f-0ba079c6e7bc)

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/119143bb-dc12-4bfd-9cd6-229d52796383)

Or perhaps, I do not completely understand your problem.
