### ISSUE TITLE
Minor consistency issue - ந்த (nda) combination - Tamil to other scripts

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#24]
In one of the Tamil verses I was transcribing to other scripts, the following phrase occurs - தொந்தந்தான் - It seems to be converted normally to Roman but when seems a little bit inconsistent when converted to Kannada or Telugu. The phrase has 2 occurrences of ந் followed by த series. However, the transcription shows them a bit differently. (Technically both approaches may be acceptable,. However, one of those is the common approach in 'modern times' and I was expecting a consistent conversion).
For example:
Tamil: தொந்தந்தான் 
Kannada: ತೊಂದನ್ದಾನ್ (I was expecting: ತೊಂದಂದಾನ್)
Telugu: తొందన్దాన్ (I was expecting: తొందందాన్ )

**Comment by virtualvinodh** [comment]
Oops!

Fixed it!

V
