### ISSUE TITLE
Baraha conversion

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#240]
Baraha conversion has issues as attached.
P,  F, U (and perhaps a few more ??) to be mapped. 

[Baraha font Conversion issues.docx](https://github.com/virtualvinodh/aksharamukha/files/11928915/Baraha.font.Conversion.issues.docx)

**Comment by virtualvinodh** [comment]
Fixed. will be pushed in the next update.

**Comment by nsesha92** [comment]
P, B per Baraha mapping not fixed.

**Comment by nsesha92** [comment]
Baraha Roman output from Baraha package uses capital letters instead of 'x'h like K for kh etc. 
Ref   https://baraha.com/help/Keyboards/kan-phonetic.htm

Both small letter combination and capital letter should be mapped for Roman (Baraha ..) conversion.

**Comment by nsesha92** [comment]
I cleared my cache and loaded aksharamukha/converted, still problem. 

Please include/update mappings for B, P, Y and R

**Comment by nsesha92** [comment]
checked now, its fixed. thanks
