### ISSUE TITLE
Issue: Rending "bh" going from Baraha to other scripts

### ISSUE THREAD

**Issue by skmnktl** [virtualvinodh/aksharamukha#251]
### TS 4.6.1.1
aSmaqnnUrjaqM parva#tE SiSriyAqNAM ~MvAtE# paqrjanyEq varu#Nasyaq SuShmE$ | 
aqdBya OSha#dhIByOq vanaqspatiqByO&dhiq saMBRu#tAqM tAM naq iShaqmUrja#M 
dhatta marutaH sa(gm) rarAqNAH || 
aSma(gg)#stEq kShudaqmuM tEq SugRu#cCatuq yaM dviqShmaH || 
saqmuqdrasya# tvAq&*vAkaqyA&gnEq pari# vyayAmasi | 
pAqvaqkO aqsmaBya(gm)# SiqvO Ba#va || 
hiqmasya# tvA jaqrAyuqNA&gnEq pari# vyayAmasi | 
pAqvaqkO aqsmaBya(gm)# SiqvO Ba#va || 
upaq - [  ] 1

### Telugu
ట్శ్ 4.6.1.1
అశ్మ॒న్నూర్జం॒ పర్వ॑తే శిశ్రియా॒ణాం ఀవాతే॑ ప॒ర్జన్యే॒ వరు॑ణస్య॒ శుష్మే᳚ .
అ॒ద్Bయ ఓష॑ధీBయో॒ వన॒స్పతి॒Bయోఽధి॒ సంBఋ॑తాం॒ తాం న॒ ఇష॒మూర్జం॑
ధత్త మరుతః స(గ్మ్) రరా॒ణాః ..
అశ్మ(గ్గ్)॑స్తే॒ క్షుద॒ముం తే॒ శుగృ॑చ్ఛతు॒ యం ద్వి॒ష్మః ..
స॒ము॒ద్రస్య॑ త్వా॒ఽ*వాక॒యాఽగ్నే॒ పరి॑ వ్యయామసి .
పా॒వ॒కో అ॒స్మBయ(గ్మ్)॑ శి॒వో Bఅ॑వ ..
హి॒మస్య॑ త్వా జ॒రాయు॒ణాఽగ్నే॒ పరి॑ వ్యయామసి .
పా॒వ॒కో అ॒స్మBయ(గ్మ్)॑ శి॒వో Bఅ॑వ ..
ఉప॒ - [ ] 1

### Roman (IAST)
ṭś 4.6.1.1
aśma̱nnūrja̱ṃ parva̍te śiśriyā̱ṇāṃ m̐vāte̍ pa̱rjanye̱ varu̍ṇasya̱ śuṣme̎ .
a̱dBya oṣa̍dhīByo̱ vana̱spati̱Byo'dhi̱ saṃBṛ̍tā̱ṃ tāṃ na̱ iṣa̱mūrja̍ṃ
dhatta marutaḥ sa(gm) rarā̱ṇāḥ ..
aśma(gg)̍ste̱ kṣuda̱muṃ te̱ śugṛ̍cchatu̱ yaṃ dvi̱ṣmaḥ ..
sa̱mu̱drasya̍ tvā̱'*vāka̱yā'gne̱ pari̍ vyayāmasi .
pā̱va̱ko a̱smaBya(gm)̍ śi̱vo Ba̍va ..
hi̱masya̍ tvā ja̱rāyu̱ṇā'gne̱ pari̍ vyayāmasi .
pā̱va̱ko a̱smaBya(gm)̍ śi̱vo Ba̍va ..
upa̱ - [ ] 1

### Roman (ISO 15919 Indic):
ṭś 4.6.1.1
aśma̱nnūrja̱ṁ parva̍tē śiśriyā̱ṇāṁ m̐vātē̍ pa̱rjanyē̱ varu̍ṇasya̱ śuṣmē̎ .
a̱dBya ōṣa̍dhīByō̱ vana̱spati̱Byō’dhi̱ saṁBr̥̍tā̱ṁ tāṁ na̱ iṣa̱mūrja̍ṁ
dhatta marutaḥ sa(gm) rarā̱ṇāḥ ..
aśma(gg)̍stē̱ kṣuda̱muṁ tē̱ śugr̥̍cchatu̱ yaṁ dvi̱ṣmaḥ ..
sa̱mu̱drasya̍ tvā̱’*vāka̱yā’gnē̱ pari̍ vyayāmasi .
pā̱va̱kō a̱smaBya(gm)̍ śi̱vō Ba̍va ..
hi̱masya̍ tvā ja̱rāyu̱ṇā’gnē̱ pari̍ vyayāmasi .
pā̱va̱kō a̱smaBya(gm)̍ śi̱vō Ba̍va ..
upa̱ - [ ] 1

**Comment by virtualvinodh** [comment]
Fixed. will be pushed in the next update.
