### ISSUE TITLE
Nandinagari font name

### ISSUE THREAD

**Issue by sridatta1** [virtualvinodh/aksharamukha#252]
https://aksharamukha.appspot.com/describe/Nandinagari
here it says that “The font used is Nandinagari Uni, which can be downloaded from [here](https://www.mediafire.com/file/33dz5wnx2uig28o/nandinagariuni.zip/file).”
But Noto font is used, so the text can be updated

**Comment by virtualvinodh** [comment]
Fixed. Will push it in the next update.
