### ISSUE TITLE
Word file conversion problems

### ISSUE THREAD

**Issue by uberize** [virtualvinodh/aksharamukha#255]
Of late, the Word file conversion has not been working reliably.

For example, IAST to Devanagari conversion of the attached slokas works flawlessly in text mode, but fails when presented as a Word file.

<img width="1135" alt="Screenshot 2023-11-25 at 10 56 34 AM" src="https://github.com/virtualvinodh/aksharamukha/assets/10455605/cd75496c-afe9-49bc-aaeb-9acc1d7b17b0">
[sample.docx](https://github.com/virtualvinodh/aksharamukha/files/13464560/sample.docx)
[IAST_Devanagari_sample.docx](https://github.com/virtualvinodh/aksharamukha/files/13464561/IAST_Devanagari_sample.docx)

**Comment by virtualvinodh** [comment]
will be fixed in the next update.
