### ISSUE TITLE
Add output option : retain । and ॥ while converting from Devanagari 

### ISSUE THREAD

**Issue by chandrasekharanr** [virtualvinodh/aksharamukha#256]
When I convert the following text --

सान्द्रानन्दावबोधात्मकमनुपमितं कालदेशावधिभ्यां
निर्मुक्तं नित्यमुक्तं निगमशतसहस्रेण निर्भास्यमानम् **।**
अस्पष्टं दृष्टमात्रे पुनरुरुपुरुषार्थात्मकं ब्रह्मतत्त्वं
तत्तावद्भाति साक्षाद्गुरुपवनपुरे हन्त भाग्यं जनानाम् **॥**

to Roman IAST, I get --

sāndrānandāvabodhātmakamanupamitaṃ kāladeśāvadhibhyāṃ
nirmuktaṃ nityamuktaṃ nigamaśatasahasreṇa nirbhāsyamānam **.**
aspaṣṭaṃ dṛṣṭamātre punarurupuruṣārthātmakaṃ brahmatattvaṃ
tattāvadbhāti sākṣādgurupavanapure hanta bhāgyaṃ janānām **..**

I would like to preserve the । and ॥ in the Roman text as well and do not want it to be . and .. 

Can you please add a checkbox in the output options to preserve the dandAs?

Thanks!

**Comment by chandrasekharanr** [comment]
Looks like this is similar to issue #232

**Comment by virtualvinodh** [comment]
You now have a toggle in output options.

![image](https://github.com/virtualvinodh/aksharamukha/assets/1050975/52605dee-69f2-4797-b1bf-44f1ef782235)
