### ISSUE TITLE
Capital letters sometimes ignored

### ISSUE THREAD

**Issue by buddhist-uni** [virtualvinodh/aksharamukha#257]
Typing my name "Khemarato" in Roman, the capital K is ignored and it was transliterated as "hemarato"   For Roman scripts where capitalization is not semantic, you should probably convert the input to lowercase before transliterating.

**Comment by virtualvinodh** [comment]
I do it already. But it depends upon the scheme.

IAST/ISO are case-in-sensitive but Harvard-Kyoto/ITRANS are case-sensitive and the mapping varies.

Could you tell me what input scheme that you're using?

V
