### ISSUE TITLE
itrans ## toggle is not processed

### ISSUE THREAD

**Issue by vpysb** [virtualvinodh/aksharamukha#258]
rAma ##( test )## rAma is translated as [[०, "राम "], [२, " राम"]].
It should have been राम (test) राम

**Comment by juniorRANJEET** [comment]
> rAma ##( test )## rAma is translated as [[०, "राम "], [२, " राम"]].
> It should have been राम (test) राम


Devanagari to Tirhuta(maithili) not working
Please solve it

**Comment by virtualvinodh** [comment]
I think I fixed it. It works at my end. It should be fixed in the next version.

**Comment by nsesha92** [comment]
Still same issue, please review.

![image](https://github.com/virtualvinodh/aksharamukha/assets/33624096/9c327696-ce68-4dd3-8071-5863e0d95c6e)
