### ISSUE TITLE
Add support for Kawi Unicode

### ISSUE THREAD

**Issue by tommai4881** [virtualvinodh/aksharamukha#259]
Now Unicode fully supports Unicode, thats mean aksharamukha kawi converter must be updated to include Kawi Unicode.
the Unicode font for Kawi is Noto Sans Kawi

**Comment by szepeviktor** [comment]
> Now Unicode fully supports Unicode

@tommai4881 Do you mean Kawi?

**Comment by tommai4881** [comment]
Yess

**Comment by virtualvinodh** [comment]
Done!

**Comment by tommai4881** [comment]
𑼒𑼱𑼶𑼲𑽁 𑼡𑽀𑼬𑼶𑼪 𑼄𑼒𑽂𑼯𑼬𑼪𑼸𑼓!
