### ISSUE TITLE
ISO15919 input option

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#265]
prapatti.com uses ṃ in ISO15919

श्रीमच्छ्रीवासयोगीश्वर महितमहा -
सṃप्रदायैकनिष्ठṃ

Also, ṛ is used for ृ
Example - https://www.prapatti.com/slokas/english/andavan_ashramam_taniyan.pdf

Can you add an input option to handle that?

Also could you add an input option to IAST where e is taken as ऎ ? (same doc)

**Comment by virtualvinodh** [comment]
fixed. It should work even without any options.
