### ISSUE TITLE
Burmese tall ā <ါ> for <-ṅg-> combination

### ISSUE THREAD

**Issue by aunghtinkyaw** [virtualvinodh/aksharamukha#27]
Per Burmese spelling convention, the IAST combination ⟨-ṅg-⟩ should also have the tall ā ⟨ ါ ⟩ligature, regardless of the consonant following the ⟨g-⟩. (e.g., saṅgrāma → သင်္ဂြါမ, not သင်္ဂြာမ. Thanks!

**Comment by virtualvinodh** [comment]
Is it the application for combinations without ṅ such as <gr> as well?

Should it be ဂြာမ or ဂြါမ?

V

**Comment by aunghtinkyaw** [comment]
That's correct. grāma would be ဂြါမ. Tall ā ⟨ ါ ⟩ is principally used to disambiguate the letters kha ⟨ခ⟩, ga ⟨ဂ⟩, ṅa ⟨င⟩, da ⟨ဒ⟩, pa ⟨ပ⟩ and va ⟨ဝ⟩, which would otherwise resemble other existing letters like ⟨ဆ⟩, ⟨က⟩, ⟨အ⟩, ⟨ဟ⟩, and ⟨တ⟩.

Great work, by the way!

**Comment by virtualvinodh** [comment]
I am currently fixing this.

So, I'd assume ဂျာ <gyā> retains the normal ā, as there is no need for disambiguation.

And all other letters for except 'ga', take the normal ā with <r>

V

**Comment by virtualvinodh** [comment]
I have fixed this for ga. If you do have comments for other consonants, please do let me know
