### ISSUE TITLE
ITRANS mapping for Tamil letters

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#28]
Please correct the following key mappings to be consistent with current ITRANS coding:

Letter | AM | ITRANS
-- | -- | --
ழ | Za | zha
ன | n^a | ^na
ற | r^a | Ra

Thanks
Seshadri

**Comment by virtualvinodh** [comment]
I have fixed this.

I have also changed the short vowels to ^e and ^o according to the document here:

https://www.aczoom.com/itrans/online/

https://docs.google.com/spreadsheets/d/14wZl8zCa4khZV3El2VGoqurKBLGx21mbS-yORi4w7Qo/edit#gid=0

See the latest mapping here:

http://aksharamukha.appspot.com/#/roman

V
V

**Comment by nsesha92** [comment]
Thanks for the update, appreciate it.

Still one change that needs to be made for ITRANS coding consistency:

Ra = ற =   ऱ

*Ra* & NOT *^ra.*

Other difference is:

input IT AM
a.e ॲ अ।ए
a.c ऍ ऍ
A.c ऑ ऑ

Ideally it should be

input output
a.c ॲ
e.c ऍ
A.c ऑ

.c being candra.

--------------
Warm regards
Seshadri

**Comment by virtualvinodh** [comment]
Fixed again.

My scheme doesn't allow ॲ as of now. I'll add it later.

V

**Comment by nsesha92** [comment]
Thanks for fixing it. Checked it now.
--------------
Warm regards
Seshadri

**Comment by the-solipsist** [comment]
Currently the ITRANS spreadsheet makes
o = ஒ
O/oo = ஓ

However, in Aksharamukha,
o = ஓ
^o / O = ஒ

This discrepancy is true of all the South Indian scripts.

While the Aksharamukha scheme makes sense (it doesn't have to divide things up into "roman" and "roman-south" the way ITRANS does), the fact remains that the "ITRANS" option in Aksharamukha doesn't match up to the official ITRANS specification.

Perhaps you could consider adding a compatibility toggle to Aksharamukha.

**Comment by virtualvinodh** [comment]
@the-solipsist 

You already can do that.

![image](https://user-images.githubusercontent.com/1050975/129114132-ce8d5860-5e3f-4661-8787-a7b6d5fffc4b.png)

There is a toggle to swap e/E for short/long distinction.

V

**Comment by nsesha92** [comment]
e/E, o/O toggle tick option already available at the bottom of
aksharamukha. Introduced couple of years ago.

**Comment by nsesha92** [comment]
No,  Currently the ITRANS maps them WRONGLY:

O/oo =  ஒ (so called short o)
o =  ஓ

and the same for e/E.

Why this newly introduced North-South divide on coding? As such we have
toooo many such divides ( thanks to British-Raj rule).

If A=B and A=C, then B should be = C

e = எ
e = ए
But எ is not = ए
எ should be = ऎ

Because of this many pure Tamizh slokas ( Divyaprapandam) etc have been
typed wrongly:

பலகோடி  as पलकॊडि ( பலகொடி) etc.

I had pointed this out to ITRANS way back in early/mid 2016, when the new
itrans/online was coded. But could not make him understant / convince him
to make the changes.

Anyway, as mentioned, Aksharamukha has implemented the "switch" option.
--------------
Warm regards
Seshadri

**Comment by the-solipsist** [comment]
Thank you, @nsesha92 and @virtualvinodh.  I think I was facing the problem while using ITRANS as an _output_ format and not as an _input_ format.  The "E/O for long, e/o for short" switch is only present when ITRANS is an input format.

@nsesha92, interestingly, the [transliteration guide for the DHARMA Project](https://hal.archives-ouvertes.fr/halshs-02272407v3/document) (section 3.2) takes a similar approach of using different representations for languages that have long & short e/o and those that don't:

> - when transliterating a language that does not make a distinction between long and short e and o, use these Latin characters without a macron
>   - this corresponds to Option 9.1 of the ISO15919 standard, applicable to languages that do not make a distinction between the phonemes e/ē and o/ō
> - however, for Dravidian languages that distinguish long and short e and o, you have the option to record that distinction even if it is not present in the script you are working with
>   - in this case, transcribe long vowels as ē/ō even in strict transliteration
>   - these characters will be treated as shorthand, subsequently to be automatically expanded with XML markup signifying that e or o was in fact inscribed, but the spelling has been normalised by the editor
>   - that is to say, the palaeographically primary generic vowel marker, e.g. that in ெக ke, ெகா ko, may represent either a short or a long vowel; when it represents a long vowel, this will be shown as an editorial normalisation, e.g. to ேக kē, ேகா kō
>   - should your inscription (or manuscript) explicitly distinguish between short and long e/o, please contact us to devise a solution for handling this
