### ISSUE TITLE
Interweave Transliteration

### ISSUE THREAD

**Issue by snippet-java** [virtualvinodh/aksharamukha#3]
Many times there is a need to have the source and target transliteration interweaved. The grouping of the interweaving could be based on two or more continuous new line occurrences. Having this feature was very useful in itranslator. So identify not just text to convert, but also the group of such to transliterate and keep source and target together - while continuing to preserve other non source text in encoding.

Let us see an example.

धृतराष्ट्र उवाच ।

धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः ।
मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ॥ १-१॥

Dhritarāshtra said:

1.  What  did  my  people  and  the  Pandavas  do,  O  Sanjaya,  gathered  together  on  the  holy  field  of Kurukṣettra, eager for battle?

====== current devanagri to iast  ====

dhṛtarāṣṭra uvāca .

dharmakṣetre kurukṣetre samavetā yuyutsavaḥ .
māmakāḥ pāṇḍavāścaiva kimakurvata sañjaya .. 1-1..

Dhritarāshtra said:

1. What did my people and the Pandavas do, O Sanjaya, gathered together on the holy field of Kurukṣettra, eager for battle?

====== proposed interweaved devanagri to iast  ====

धृतराष्ट्र उवाच ।

dhṛtarāṣṭra uvāca .

धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः ।
मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ॥ १-१॥

dharmakṣetre kurukṣetre samavetā yuyutsavaḥ .
māmakāḥ pāṇḍavāścaiva kimakurvata sañjaya .. 1-1..

Dhritarāshtra said:

1.  What  did  my  people  and  the  Pandavas  do,  O  Sanjaya,  gathered  together  on  the  holy  field  of Kurukṣettra, eager for battle?

**Comment by virtualvinodh** [comment]
Try this here:

http://aksharamukha.appspot.com/composer

Mark the sample portion to be translated as below with # and the second the secondary script as Devanagari and IAST.  (and of course the input as Devanagari as well)

-------------------------

#धृतराष्ट्र उवाच ।#

#धर्मक्षेत्रे कुरुक्षेत्रे समवेता युयुत्सवः ।
मामकाः पाण्डवाश्चैव किमकुर्वत सञ्जय ॥ १-१॥#

Dhritarāshtra said:

What did my people and the Pandavas do, O Sanjaya, gathered together on the holy field of Kurukṣettra, eager for battle?

-------------------

**Comment by snippet-java** [comment]
It works beautifully. Fantastic !

**Comment by anantakrishna** [comment]
> Try this here:
> 
> http://aksharamukha.appspot.com/composer

Is composer available via API? There is nothing about it on the page http://aksharamukha.appspot.com/web-api.

Particularly, I need a secondary text to stay untouched.
