### ISSUE TITLE
Consider working with Wikipedia on a MediaWiki implementation

### ISSUE THREAD

**Issue by rrcha** [virtualvinodh/aksharamukha#30]
This is an excellent project which could be used for so many different languages on Wikipedia which are written with more than one script, including Konkani, Javanese, Punjabi, Sanskrit, Sindhi, Hindi-Urdu and Kashmiri.

If it could be implemented in MediaWiki, it could be a great solution to the challenges of digraphia on the platform.

**Comment by virtualvinodh** [comment]
There is now a REST API for reasonable public use and also a python package.

It is up to developers to use develop their own plugins.

http://aksharamukha.appspot.com/#/web-api

http://aksharamukha.appspot.com/#/python

V
