### ISSUE TITLE
A Way to Enter ஃ (ஆய்த எழுத்து)

### ISSUE THREAD

**Issue by msr24** [virtualvinodh/aksharamukha#33]
Sorry if this is not an issue. Did not know if there is a board to ask for help.  I could not find a way to type அஃது,  இஃது, etc. 

I typed aqatu in HK and corrected it by deleting.

**Comment by virtualvinodh** [comment]
It depends upon the scheme.

In HK, it is K

http://aksharamukha.appspot.com/#/describe/Tamil

Go to Others at the bottom and change the scheme in the right-hand corner to see the equivalent of Aytham in that particular scheme.

V

V
