### ISSUE TITLE
RFE - Please add a copy button on the input side as well

### ISSUE THREAD

**Issue by msr24** [virtualvinodh/aksharamukha#34]
First of all, this is a FANTASTIC app. Thanks for creating this.  

If time permits, please add a copy button on the input side too.  

Use case: I type on the input side and for the sake of completeness (old habits die hard), save the input as well.  We can do this by cntrl + C. But the button on the right-hand side is very convenient. A similar one on the left will be nice. 

Priority - low

**Comment by virtualvinodh** [comment]
Done. I have now added a button
