### ISSUE TITLE
अं as ȧ  in IAST transliteration instead of aṃ  

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#38]
Since अं has dual sound ȧ is preferred in IAST transliteration instead of aṃ . This applies to all 
ं, ँ vowels. This option may shorten transliterated text for print media.

 आं  इं ईं उं ऊं   एं ऐं ओं औं           अँ आँ इँ ईँ उँ ऊँ एँ 
 ȧ   ā̇   ï  ī̇  u̇ ū̇  ė aï  ȯ  au̇       a̐  ā̐  i̐  ī̐ u̐ ū̐  e̐

Gȧgā (गंगा) /  Gaṅgā (गङ्गा)
Kā̇cana (कांचन)     / Kāñcana (काञ्चन )
Pā̇ḍava (पांडव)    /  Pāṇḍava (पाण्डव)
Su̇dara (सुंदर)   /  Sundara (सुन्दर)
Gȧbhīra (गंभीर ) /  Gambhīra (गम्भीर)

अनुच्छेद 1 (एक) – सभी मनुष्यों को गौरव और अधिकारों के विषय में जन्मजात स्वतन्त्रता और समानता प्राप्त हैं। उन्हें बुद्धि और अन्तरात्मा की देन प्राप्त है और परस्पर उन्हें भाईचारे के भाव से बर्ताव करना चाहिए।

Anuccheda 1 (Eka) – Sabhī manuṣyȯ ko gaurava aura adhikārȯ ke viṣaya mė janmajāta svatantratā aura samānatā prāpta haï . Unhė buddhi aura antarātmā kī dena prāpta hai aura paraspara unhė bhāīcāre ke bhāva se bartāva karanā cāhie.

**Comment by virtualvinodh** [comment]
Probably, I can add an option to upload custom mapping. But I won't be adding this option per se

V
