### ISSUE TITLE
Tamil to Telugu transcription of trill Ra (ṟ) series

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#4]
Transcription where Tamil is the source (input) language:
The trill Ra (ṟ) series - vallina Ra series (ற etc) - is getting transcribed as common (idaiyina) ra (ர) in Devanagari, Telugu & Kannada.
This behavior is different from older version of aksharamukha. 
Ideally, an option can be provided to the user - to control the handling of vallina Ra series of Tamil - whether they should be preserved suitably in the target language or converted as the common 'ra' series in the target language.

(The combinations of RRa (ற்ற), nRa (ன்ற) series gets transcribed acceptably as tra, ndra series in these target languages. No change needed for that scenario)

**Comment by virtualvinodh** [comment]
I have reverted to preserving the hard 'ra'.
