### ISSUE TITLE
Multiple scripts support

### ISSUE THREAD

**Issue by virtualvinodh** [virtualvinodh/aksharamukha#41]

**Comment by geethub** [comment]
Please keep the old version to solve the India's linguistic problem. You may add  three more out put text areas so people can type in sound based typing-key strokes (ie. a,aa,i,ii/ee,u,uu/oo,ae,e,ai,aw,o,au,a.m,a.c,a.h,Ah) to get transliteration in IAST,IPA(**vowels)only**) and two vernacular languages.
meraa bhaarata mahana hai .
merā bhārata mahana hai .
meːɾɑː bhɑːɾətə məɦənnə ɦəɪ .
मेरा भारत महन है ।
மேரா பா⁴ரத மஹன ஹை .
