### ISSUE TITLE
Additional Ol Chiki characters

### ISSUE THREAD

**Issue by teresaejunior** [virtualvinodh/aksharamukha#43]
While trying to convert pieces from [Romanized Santhali](https://www.bible.com/bible/1538/MAT.1), some characters like **ạ** and **ō** are skipped.

According to [this page](https://www.cambridge.org/core/journals/modern-asian-studies/article/from-language-to-script-graphic-practice-and-the-politics-of-authority-in-santalilanguage-print-media-eastern-india/0F7A07B50B16D94C1BF2E4A983EFBB64), the Roman script uses diacritics to distinguish **long vowels (o, ō) ‘reduced’ vowels (a, ạ)**, glottalized stops (t’, c’, k’, p’), and palatal nasals (ń).

Thanks for your attention!

**Comment by virtualvinodh** [comment]
I see.

Could you send me a sample text in both scripts? I can use it to test my code.

And give the mappings for (t’, c’, k’, p’) and ạ  and ń.

Have a look at the mapping here:

http://aksharamukha.appspot.com/#/describe/Santali
(Select ISO from the drop-down list)

Does it have all the necessary characters? or am I missing something?

I probably have to customize the mapping to get what you want. 

V

**Comment by teresaejunior** [comment]
Unfortunately, I have found too little information on these characters. They are part of the the first Santhali alphabet created in the 1890s. It seems they are mostly unused in the modern Santali Latin alphabet, since I couldn't find them in any transliteration tables, which is a pity, since it becomes impossible to convert all Santali literature.

https://www.loc.gov/catdir/cpso/romanization/santali.pdf seems to indicate that these markers can simply be ignored in transliteration. For example the word B**ạ**ibel, if simply transliterated as B**a**ibel, becomes "ᱵᱟᱭᱵᱮᱞ", which is a valid translation for Bible, and can be found in https://sat.wikipedia.org/wiki/ᱤᱥᱟᱹᱭ_ᱫᱷᱚᱨᱚᱢ

It would be best if I could find a native speaker who can verify this.

**Comment by virtualvinodh** [comment]
https://theofdn.org/people/

Try contacting someone from here. 

Particularly, Ramjit Tudu. He seems to be a native Santali speaker.

V

**Comment by teresaejunior** [comment]
Pinging @hpnrt (Ramjit Tudu), @coldbreeze16 (Dr. Nasim Ali), and @gyan111 (Jnanaranjan Sahu). Can any of you please help us with converting these characters from Romanized Santali to Ol Chiki? 

This is a list I compiled of non-ascii characters found in the text that can't be converted at http://aksharamukha.appspot.com/converter#/describe/Santali, from Roman (ISO 15919) to Santali (Ol Chiki):

- Ạḍi (**Ạ** / `&#7840;`)
- Ḍubạ (**ạ** / `&#7841;`)
- ãṭ (**ã** / `&#227;`)
- tahẽkante (**ẽ** / `&#7869;`)
- hĩs (**ĩ** / `&#297;`)
- nehõrok̕a (**õ** / `&#245;` + **k̕** / `k&#789;`)
- kũnḍe (**ũ** / `&#361;`)
- Ńel (**Ń** / `&#323;`)
- iń (**ń** / `&#324;`)
- up̕ (**p̕** / `p&#789;`)
- akat̕ (**t̕** / `t&#789;`)
- kisạ̃ṛ (**ạ̃ṛ** / `&#7841;&#771;&#7771;`)
- manwako (**w**)
- Ṭhik
- seṅgelreko
- acʼakʼ

Thank you very much!

**Comment by teresaejunior** [comment]
BTW, it was Google Keyboard that converted "Baibel" to  "ᱵᱟᱭᱵᱮᱞ". aksharamukha converted 
it to "ᱵ**ᱚᱤ**ᱵᱮ**ᱹ**ᱞ". I don't understand what's the difference.

**Comment by coldbreeze16** [comment]
Ramjit is a native speaker, he should be able to helo. I am not very fluent
with Ol chiki.

**Comment by hpnrt** [comment]
> Pinging @hpnrt (Ramjit Tudu), @coldbreeze16 (Dr. Nasim Ali), and @gyan111 (Jnanaranjan Sahu). Can any of you please help us with converting these characters from Romanized Santali to Ol Chiki?
> 
> This is a list I compiled of non-ascii characters found in the text that can't be converted at http://aksharamukha.appspot.com/converter#/describe/Santali, from Roman (ISO 15919) to Santali (Ol Chiki):
> 
> * Ạḍi (**Ạ** `&#7840;`)
> * Ḍubạ (**ạ** `&#7841;`)
> * ãṭ (**ã** `&#227;`)
> * tahẽkante (**ẽ** `&#7869;`)
> * hĩs (**ĩ** `&#297;`)
> * nehõrok̕a (**õ** `&#245;` + **k̕** `k&#789;`)
> * kũnḍe (**ũ** `&#361;`)
> * Ńel (**Ń** `&#323;`)
> * iń (**ń** `&#324;`)
> * up̕ (**p̕** `p&#789;`)
> * akat̕ (**t̕** `t&#789;`)
> * kisạ̃ṛ (**ạ̃ṛ** `&#7841;&#771;&#7771;`)
> * manwako (**w** `w`)
> * Ṭhik
> * seṅgelreko
> * acʼakʼ
> 
> Thank you very much!

Sorry for delay in reply. following are conversion of those characters.

Ạ = ạ = ᱟᱹ (Ạḍi= ᱟᱹᱰᱤ)
ã = ᱟᱸ (ãṭ= ᱟᱸᱴ)
ẽ = ᱮᱸ (tahẽkante= ᱛᱟᱦᱮᱸᱠᱟᱱᱛᱮ)
ĩ = ᱤᱸ (hĩs= ᱦᱤᱸᱥ)
õ = ᱚᱸ (nehõrok̕a= ᱱᱮᱦᱚᱸᱨᱚᱜᱼᱟ)
ũ = ᱩᱸ 
Ń = ń = ᱧ (Ńel=ᱧᱮᱞ , iń= ᱤᱧ)
p̕ = ᱵ (up̕= ᱩᱵ)
t̕ = ᱫ (akat̕=ᱟᱠᱟᱫ)
ạ̃ = ᱟᱺ , ṛ=ᱲ , (ạ̃ṛ=ᱟᱺᱲ)
w = ᱣ (manwako=ᱢᱟᱱᱣᱟᱠᱚ)
Ṭ = ᱴ (Ṭhik=ᱴᱷᱤᱠ)
ṅ = ᱝ (seṅgelreko= ᱥᱮᱝᱜᱮᱞᱨᱮᱠᱚ)
cʼ=ᱡ , kʼ=ᱜ

There have another rule: If there have any **vowel** after **kʼ,cʼ,t̕ ,p̕** , then a **ᱼ** (PHHARKA  `&#7292;`) will be placed between them.
_example_ : nehõrok̕a= ᱱᱮᱦᱚᱸᱨᱚᱜᱼᱟ  (**k̕a=ᱜᱼᱟ**)

**Comment by teresaejunior** [comment]
I had a look at [script_mapping.json#L11149](https://github.com/virtualvinodh/aksharamukha/blob/master/aksharamukha-back/resources/script_mapping/script_mapping.json#L11149), and I couldn't really understand how the mappings are done.

**Comment by virtualvinodh** [comment]
@teresaejunior 

I follow a custom scheme by dividing the characters into distinct chunks: Main Vowels, South Indic Vowels, Modern Vowels, Sinhala Vowels, Main Consonants, South-Indic Consonants, Sinhala Consonants, Perso-Arabic Consonants, Combining Marks, etc.

Thus each character has a specific chunk and an index. santali.consonants.main[0] will always be ᱠ and so on.

V

**Comment by janilam** [comment]
> script_mapping.json#L11149

@hpnrt When do I use "ᱽ"? 
This is my attempt:
content = re.sub("kʼ", "ᱜᱽ", content)
content = re.sub("cʼ", "ᱡᱽ", content)
content = re.sub("tʼ", "ᱫᱽ", content)
content = re.sub("pʼ", "ᱵᱽ", content)
content = re.sub("ẖʼ", "ᱦᱽ", content)
