### ISSUE TITLE
Urdu Transliteration

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#46]
زبان اسکولوں میں زبانیں سیکھنا ان لوگوں کے لیے ایک عظیم اختیار ہوتا ہے جو کسی زبان کو تنہا نہیں سیکھنا چاہتے ہیں۔ بہت سارے لوگ دوسروں کے ساتھ بہتر طور پر سیکھتے ہیں۔

ज़बान असकवलवं मयं ज़बानयं सयखना अन लवगवं के लये अयक अज़यम अख़तयार हवता हे जव कसय ज़बान कव तनहा नहयं सयखना चाहते हयं। बहत सारे लवग दवसरवं के साथ बहतर तवर पर सयखते हयं।

Other Website Transliteration:
ज़बान स्कूलों में ज़बानें सीखना उन लोगों के लिए एक अज़ीम इख़तियार होता है जो किसी ज़बान को तन्हा नहीं सीखना चाहते हैं। बहुत सारे लोग दूसरों के साथ बेहतर तौर पर सीखते हैं।

**Comment by virtualvinodh** [comment]
I don't support guessing short vowels.

It is beyond the scope for this converter.  A proper Urdu to Devangari will involve some lexical lookup.

As such, I just do a literal transliteration of what is written in Perso-Arabic (not showing short vowels and retaining consonants even when they are used to denote vowels)

V

**Comment by geethub** [comment]
A Hindi to Urdu Transliteration System 
http://www.learnpunjabi.org/pdf/paper248.pdf

**Comment by geethub** [comment]
अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः
क ख ग घ ङ च छ ज झ ञ 
ट ठ ड ढ ण त थ द ध न प फ ब भ म
य र ल ळ व ह श ष स
क़ ख़ ग़ ज़ ड़ ढ़ फ़ ऱ ऴ
अं आं इं ईं उं ऊं एं ऐं ओं औं

To Urdu transliteration:
اَ آ اِ ئي اُ ؤ ر اي اَي او ائو ئا ا
ڪ ک گ گھ ڱ چ ڇ ج جھ ڃ
ٽ ٺ ڊ ڍ ڻ ته ٿ د ڌ نه پ ڦ به ڀ م
ي ر ل ل و ھ ش ش س
ڪ خ غ ز ڙ ڙھ ف
ان آن ان اين ان اون ۽ ۽ اون اون

Back to Hindi transliteration
अ आ इ ई उ ऊ र ए ऐ ओ इओ आ अलिफ़ु
कि ख ग घ ङ च छ ज झ ञ
ट ठ ड ढ ण त थ द ध न प फ बि भ म
य र ल ल व ह ष ष स
कि ख़ ग़ ज़ ड़ ढ़ फ़
इन आन उन एन उन ओन ऐं ऐं ओन ओन

**Comment by geethub** [comment]
ज़बान स्कूलों में ज़बानें सीखना उन लोगों के लिए एक अज़ीम इख़तियार होता है जो किसी ज़बान को तन्हा नहीं सीखना चाहते हैं। बहुत सारे लोग दूसरों के साथ बेहतर तौर पर सीखते हैं।

To Urdu Transliteration.
زبان اسکولوں میں زبانیں سیکھنا ان لوگوں کے لیے ایک عظیم اختیار ہوتا ہے جو کسی زبان کو تنہا نہیں سیکھنا چاہتے ہیں۔ بہت سارے لوگ دوسروں کے ساتھ بہتر طور پر سیکھتے ہیں۔

Back to Urdu:
ज़बान स्कूलों में ज़बानें सीखना उन लोगों के लिए एक अज़ीम इख़तियार होता है जो किसी ज़बान को तन्हा नहीं सीखना चाहते हैं। बहुत सारे लोग दूसरों के साथ बेहतर तौर पर सीखते हैं
