### ISSUE TITLE
Baraha input converter (including vedic style)

### ISSUE THREAD

**Issue by snippet-java** [virtualvinodh/aksharamukha#47]
Since baraha source files are quite common, it would be extremely valuable to have that as an acceptable input source. It will be a boon to people who dont have Baraha and also along with it would be good if it can support Vedic style input as part of it.

**Comment by virtualvinodh** [comment]
I need some sample files.

What is that that makes Baraha source files special?

**Comment by uberize** [comment]
Here is a sample: https://drive.google.com/file/d/1vmSFkMVrYcu-vlBLh_jpnCx-ANfMM7ZY/view?usp=sharing

Baraha (www.baraha.com) is Windows application software that has been around for a long time and has been used to typeset various Indic documents. It uses an ASCII-based transliteration scheme that is similar to ITRANS but differs in some respects. See http://baraha.com/v10/help/Keyboards/dev_phonetic.htm for the Devanagari mapping. 

Using the Baraha editor, you can type Indic text using this mapping and see the output in Devanagari, Marathi etc. You can save your input text into a text file (the software gives it the extension .brh, see link above). Hope this helps.

**Comment by snippet-java** [comment]
Any chance for consideration ? Thanks for your valuable time.

**Comment by virtualvinodh** [comment]
fixed

**Comment by uberize** [comment]
Thank you Vinodh
