### ISSUE TITLE
vue template compiler

### ISSUE THREAD

**Issue by lalitaalaalitah** [virtualvinodh/aksharamukha#48]
While the old version compiles and run fine, I face the below quoted error while compiling and running the new one:
```
`Module build failed (from ./node_modules/vue-loader/lib/index.js):
  Error: [vue-loader] vue-template-compiler must be installed as a peer dependen  cy, or a compatible compiler implementation must be passed via options.
  
  - index.js:21 loadTemplateCompiler
    [aksharamukha-front]/[vue-loader]/lib/index.js:21:11
  
  - index.js:65 Object.module.exports
    [aksharamukha-front]/[vue-loader]/lib/index.js:65:35`
```
I tried some solutions available on internet, but they are not helping in this case.

**Comment by virtualvinodh** [comment]
What version of Quasar are you using?

V

**Comment by virtualvinodh** [comment]
You can run the system with Docker without any configuration.

http://aksharamukha.appspot.com/download

I am closing down the issue.
