### ISSUE TITLE
Titus: support accents.

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#49]
Example text from http://titus.uni-frankfurt.de/texte/etcs/ind/aind/ved/yvw/sbm/sbm.htm : 

> réta eva táddʰatte yadā́jyamucʰiṣyáte téna raśanā́mabʰyajyā́datte téjo vā ā́jyam prājāpatyó'śvaḥ prajā́patimeva téjasā sámardʰayatyápūto vā́ eṣò'medʰyo yadáśvaḥ

**Comment by virtualvinodh** [comment]
Would you happen to know the Devanagari mapping to those accents?

V

**Comment by vvasuki** [comment]
In general, this is the scheme: the two accents you see in abhī̀mám are svarita and udAtta respectively.

 in case of shatapatha brAhmaNa, just map the accent in á to  ᳘. Only complicating factor is that you need to preprocess vowels like á to some intermediate representation like a followed by https://www.fileformat.info/info/unicode/char/00b4/index.htm

**Comment by vvasuki** [comment]
For the more general case, one would need to place svarita and anudAtta symbols on the devanAgarI syllables surrounding the one with the acute accent in the roman representation - so that can be pretty complicated . But even decomposing accented vowels like á would make Titus transliterator functional and is a great first step (users would then have to just replace the accents separately themselves).

**Comment by virtualvinodh** [comment]
@vvasuki Is the same issue as https://github.com/virtualvinodh/aksharamukha/issues/86? in terms of mapping that is.

V

**Comment by vvasuki** [comment]
आम्

**Comment by virtualvinodh** [comment]
Tracking this with https://github.com/virtualvinodh/aksharamukha/issues/86
