### ISSUE TITLE
Transcribing websites

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#5]
Two issues in website conversion:

a)
I tried to convert a website - a blog URL:
http://thevaramclass.blogspot.com/2018/12/351-tiru-alavay-seyyane-tiru-alavay.html

from Tamil to Telugu
with transcribe Tamil option ON.

The original web page has text in multiple languages. So, I was expecting the Tamil text strings to be converted to the target output language and all non-Tamil text in that page to remain unaffected.

The non-Tamil text remained unaffected. That is good.
But the Tamil text strings were not properly transcribed to the target language.

b)
I tried to convert a website:
http://www.ifpindia.org/digitaldb/site/digital_tevaram/U_TEV/VMS5_001.HTM

from Tamil to Telugu
with transcribe Tamil option ON.

The original web page has text in Tamil and English. Some words in the English had transliteration in ISO with diacritics - such as Kōvaiyar / Umā / etc.
I was expecting the Tamil text strings to be converted to the target output language and all non-Tamil text in that page to remain unaffected.

English text having ISO characters with diacritics are impacted and got corrupted by the transcription process.
Further, the Tamil text strings were not properly transcribed to the target language.

For example, 
=== original web site had a section like this ===
இளையார்
He is the youth
[[PP: மூப்பரின் இளையவன் (Kōvaiyar, 312) and its commentary by Pēraciriyar may be compared here.
விடம் உண்ட எம் அருத்தனார் அடியாரை அறிவரே
our Lord who has on his half Umā, and drank the poison, will know his devotees (and bestow his grace upon them)
===  converted string looked like this ===
à®à®³à¯à®¯à®¾à®°à¯
He is the youth
[[PP: à®®à¯à®ªà¯à®ªà®°à®¿à®©à¯ à®à®³à¯à®¯à®µà®©à¯ (KÅvaiyar, 312) and its commentary by PÄraciriyar may be compared here.
à®µà®¿à®à®®à¯ à®à®£à¯à® à®à®®à¯ à®à®°à¯à®¤à¯à®¤à®©à®¾à®°à¯ à®à®à®¿à®¯à®¾à®°à¯ à®à®±à®¿à®µà®°à¯
our Lord who has on his half UmÄ, and drank the poison, will know his devotees (and bestow his grace upon them)
===

**Comment by virtualvinodh** [comment]
I have fixed (b).

I am still not sure what's wrong with  (a). I think Blogspot is doing something funny with the encoding. The converter recognizes only the consonants but not the vowel signs. I will have to look into it a bit further.

**Comment by virtualvinodh** [comment]
I suppose you can use the chrome or Firefox extension for the same. The give better results. I'm closing the issue for now.
