### ISSUE TITLE
Seperate repos for chrome extension, python package.

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#52]
namaste vinoda,

Anyone wanting to examine or contribute to the chrome extension or the python package is forced to clone this repo with all its unrelated code. Best to put them in separate repos.

**Comment by vvasuki** [comment]
Plus, git root not being in the project (sub)folder is a hassle if one uses IDE-s.

**Comment by virtualvinodh** [comment]
Done. 

V
