### ISSUE TITLE
Preserve case for Roman Readable

### ISSUE THREAD

**Issue by abhayambika** [virtualvinodh/aksharamukha#54]
In the composer, I was trying devanAgari and Roman Readable. It works fine, I use it and test more Thank you.  Will it be possible to preserve the case of Roman text?

**Comment by virtualvinodh** [comment]
What do you mean exactly? Could you please give ane example input and your expected output for the same?

**Comment by abhayambika** [comment]
It was wrong testing. Please I am closing this issue.
