### ISSUE TITLE
Bengali transliteration

### ISSUE THREAD

**Issue by MatsEklof** [virtualvinodh/aksharamukha#55]
I have tried to type Bengali script and convert to Roman (IAST). 
For example this works fine:
কোল   kola
But when I input jpg photo of Bengali script then there is an error with the letter o (in the Bengali word tomara). See screenshot. I tried different Roman scripts,  but it did not change the result. 
![Screenshot_20200126-142917](https://user-images.githubusercontent.com/60312490/73133100-22926b00-404a-11ea-8397-fed998d1c39e.jpg)

**Comment by MatsEklof** [comment]
The correct spelling output would be 
tomāra

**Comment by virtualvinodh** [comment]
Fixed
