### ISSUE TITLE
Roman Readable - short / long vowels of E and O

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#56]
The Roman Readable transcription seems to be oriented towards North Indian languages - that do not have short vowels of e (எ) & o (ஒ).
When transcribing source Tamil text to Roman Readable target, I am unable to distinguish between the short and long forms of these vowel sounds in the target text.

For example:
Source: Tamil: தோடு உடைய செவியன், விடையேறி, ஓர் தூ-வெண்-மதிசூடிக்
Target: Roman readable: tod'u ud'aiya seviyan, vid'aiyeri, or too-ven-madisood'ik

If this can be improved, then it will be more useful when transcribing south indian language to Roman Readable.

**Comment by thevaram-class** [comment]
Further, I realized that even ல் / ள difference is not handled in the target. (even though ழ is handled)!
பால் / பாழ் === paal / paazh
கல் / கள் ===  kal / kal

**Comment by virtualvinodh** [comment]
I have added options for these.
