### ISSUE TITLE
Roman (Readable) - Tamil transcription - refinements to improve usability

### ISSUE THREAD

**Issue by thevaram-class** [virtualvinodh/aksharamukha#57]
**For Tamil to Readable Roman**
I suggest the following mapping for Tamil transcription into Readable Roman:

ந / ன = n - No distinction in the transcription.
Retroflex ண் = N
ர / ற = r / R - ( user option - no distinction in the final transcribed text) 
ல / ள / ழ = l / L / zh

For the following vowels 
Short எ = e
Long ஏ =   E 
Short ஒ = o
Long ஓ =  O 

Tamil | Readable Transcription
அ | a
ஆ | aa
இ | i
ஈ | ee
உ | u
ஊ | oo
எ | e
ஏ | E 
ஐ | ai
ஒ | o
ஓ | O 
ஔ | au
ஃ | h

க் | k
ங் | ng
ச் | ch
ஞ் | nj
ட் | t
ண் | N
த | th
ந் | n
ப் | p
ம் | m
ய் | y
ர் | r
ல் | l
வ் | v
ழ் | zh
ள் | L
ற் | R (user option - r )
ன் | n

க 				(when sounds likes ga - ex: வேகம்) | ga
ச 				(when sounds like sa - ex: பாசம்) | sa
ச 				(when sounds like ja - ex: அஞ்சு) | ja
ட 				(when sounds like da - ex: படம்) | da
த 				(when sounds like dha - ex: பந்து) | dha
ப 				(when sounds like ba - ex: அம்பு) | ba

**Special handling of some combinations |**  
ற்ற 				(ex: பற்று) | tra
ன்ற 				 (ex: ஒன்று) | ndra
ன்க 				 (ex: நான்கு) | n-ga
ங்க 				(ex: எங்கு) | nga
ஞ்ச 				(ex: மஞ்சு) | nja
ஃக | hha
ஃத | hdha

**Examples:
Tamil | Readable Transcription**
வந்து | vandhu
வண்டு | vaNdu
அண்ணா | aNNaa
பாடம் | paadam
பாதம் | paadham
எங்கு | engu
என்க | en-ga
பஞ்சு | panju
வால் | vaal
வாள் | vaaL
வாழ் | vaazh
கரிய | kariya
சிறிய | siRiya (/ siriya)
வெற்றி | vetri
குன்று | kundru
வெல் | vel
வேல் | vEl 
கொல் | kol
கோல் | kOl 
கொள்கை | koLgai
கோள்கள் | kOLgaL 
அஃது | ahdhu
அஃறிணை | ahriNai
எஃகு | ehhu

**Here are 2 example verses:**

1.1.1
தோடு உடைய செவியன், விடையேறி, ஓர் தூ-வெண்-மதிசூடிக்
காடு உடைய சுடலைப்-பொடி-பூசி, என் உள்ளம் கவர்-கள்வன்,
ஏடு உடைய மலரான் முனை-நாள் பணிந்து ஏத்த அருள்-செய்த
பீடு உடைய பிரமா-புரம் மேவிய பெம்மான் இவன் அன்றே.

Roman Readable (proposal ):
thOdu udaiya seviyan, vidaiyERi, Or thoo-veN-madhisoodik
kaadu udaiya sudalaip-podi-poosi, en uLLam kavar-kaLvan,
Edu udaiya malaraan munai-naaL paNindhu Eththa aruL-seydha
peedu udaiya piramaa-puram mEviya pemmaan ivan andrE. 

3.49.1
காதலாகிக் கசிந்து கண்ணீர் மல்கி
ஓதுவார் தமை நன்னெறிக்கு உய்ப்பது
வேதம் நான்கினும் மெய்ப்பொருள் ஆவது 
நாதன் நாமம் நமச்சிவாயவே.

Roman Readable (proposal):
kaadhalaagik kasindhu kaNNeer malgi
Odhuvaar thamai nannerikku uyppadhu
vEdham naan-ginum meypporuL aavadhu 
naadhan naamam namachchivaayavE. 
-----------

**Comment by virtualvinodh** [comment]
The idea is not to mix uppercase and lowercase letters. It makes the text very unnatural to read. 

Perhaps, there can be another way to achieve the distinction?

**Comment by thevaram-class** [comment]
I understand your perspective on wanting to avoid use of upper case letters. 
I do not know how else to make these letters distinct in the readable transliteration. 
Whatever is the approach you figure out, it may be a good idea to see if you can provide some run time options for user to use upper case letters in these situations - to override any pre-defined defaults.

**Comment by virtualvinodh** [comment]
I am closing this. The idea of roman readable is to use a minimal amount of extra letters to make a reasonable phonetic approximation of the original text while maintaining readability. If people would like to get the exact differentiation they should ISO romanization.

**Comment by thevaram-class** [comment]
Yes, that is fine. Thanks.

V. Subramanian
