### ISSUE TITLE
ง in "Karaoke" Thai Orthography should be ṃ not ṅ

### ISSUE THREAD

**Issue by buddhist-uni** [virtualvinodh/aksharamukha#59]
"เอวัง เม" should convert to "evaṃ me" as "เอวํ เม" does, but currently I get "evaṅ me"

**Comment by virtualvinodh** [comment]
One has to reconstruct the Anusvara (ṃ). It's not simple.

Both สํก and สงฺก become 'สังกะ' and hence indistinguishable. 

If there are some common words and general heuristics, I can probably guess where ṃ initially occurred and reconstruct it.

**Comment by virtualvinodh** [comment]
This involves lots of guessing and requires some knowledge of Pali. This goes beyond the scope of transliteration.
