### ISSUE TITLE
Using Aksharmukha as typing keyboard 

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#6]
अ्‌ अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः अम्‌ अन्‌            
अं आं इं ईं उं ऊं एं ऐं ओं औं     ॐ      
अँ आँ इँ ईँ उँ ऊँ एँ 

क्‌  क ख ग घ ङ  च छ ज झ ञ  ट ठ ड ढ ण त थ द ध न 
प फ ब भ म य र ल ळ व ह श ष स क्ष ज्ञ त्र श्र 
ख़ ग़ ज़ ड़ ढ़ फ़ ऱ ऴ

VELTHUIS:  
a a aa i ii u uu .r .R e ai o au aE aO a.h am an 
a.m aa.m i.m ii.m u.m uu.m e.m ai.m o.m au.m o.m 
a~m aa~m i~m ii~m u~m uu~m e~m 

k ka kha ga gha "na ca cha ja jha ~na  .ta .tha .da .dha .na ta tha da dha na 
pa pha ba bha ma ya ra la ..la va ha "sa .sa sa k.sa j~na tra "sra 
_kha .ga za ..ra ..rha fa _ra _la

VELTHUIS transliteration can be used as KEYS STROKES in right column to type any languages in left column.
Is it possible to simplify Velthuis Keystrokes this way? 

VELTHUIS: (Modified or Typing keystrokes preferably in lower cases)
  
a.h a aa i ii u uu .r .rr e ai o au ae/aE aw/aO a.h am an
a.m aa.m i.m ii.m u.m uu.m e.m ai.m o.m au.m o.m (m=Anusvar)
a.c aa.cm i.c  ii.c u.c uu.c e.c (c=Chandrabindu) 

k.h ka kha ga gha "na cha chha ja jha/za ~na  .ta .tha .da .dha .na ta tha da dha na
pa pha/fa ba bha ma ya ra la .la va ha sha .sa sa k.sa j~na tra shra 
.kha .ga .ja ..da ..dha .fa ..ra ..la

What are your views on this Vowels Transliteration scheme?
अ आ इ ई उ ऊ ऋ ॠ ए ऐ ओ औ ऍ ऑ अः अम्‌ अन्‌
a  ā  i  ī  u ū  ṛ ṝ  e ai o au ă ŏ aḥ  am‌ an‌ 
अं आं इं ईं उं ऊं एं ऐं ओं औं  ॐ  अँ आँ इँ ईँ उँ ऊँ एँ 
ȧ ā̇   ï ī̇   u̇ ū̇ ė aï ȯ au̇   OM   a̐ ā̐  i̐  ī̐  u̐ ū̐  e̐ 
https://groups.google.com/forum/?fromgroups=#!topic/ekmanch/PDYfiv3WQzQ

**Comment by virtualvinodh** [comment]
Fixed check out. 

http://aksharamukha.appspot.com/#/input/Devanagari

**Comment by geethub** [comment]
Why create a special keyboard just for Devanagari? How about other languages?
Why not allow to customize Keyboard Scheme: AKSHARAA? One may add needed keystrokes and save the scheme. Beside AKSHARAA we don't need other schemes such as HK,ITRANS or VELTHUIS.

http://aksharamukha.appspot.com/#/input/Devanagari
