### ISSUE TITLE
Removing double letters for Takri Script

### ISSUE THREAD

**Issue by nik9hil** [virtualvinodh/aksharamukha#62]
Can we have an option to remove double consonants while transliterating? The script left the responsibility for the user to identify the presence of a double consonant. 

For example, kullU (Roman Harvard-Kyoto) is transliterated as 𑚊𑚰𑚥𑚶𑚥𑚱 (Takri) currently. Transliterating while removing the double consonant would result in 𑚊𑚰𑚥𑚱 (Takri).  
Another example: uttara (Roman Harvard-Kyoto) is transliterated as 𑚄𑚙𑚶𑚙𑚤 (Takri).  Transliterating while removing the double consonant would result in 𑚄𑚙𑚤 (Takri).

**Comment by virtualvinodh** [comment]
Sure. Would you want this to be the default? Or would you want this to be an additional option that has to be manually enabled?

On a related note: Do /buddha/ and /siddha/ become 𑚠𑚰𑚜 & 𑚨𑚮𑚜 ?

V

**Comment by nik9hil** [comment]
The example you have given might be wrong. As far as I seen in examples, double letters were omitted when it was a combination of the same consonant. /buddha/ and /siddha/ have combination of /d/ and /dha/, both being different. This can create conflicts in some situations while writing in Pahari language using Takri. I know that Gurmukhi, a sister script uses addak during such a situation. But due to the absence of anything like this in Takri, it would be better to implement this feature for double letter with same consonant. Samples being scarce, it would be better if this could be consulted with a third person also.
Combined with the fact that today all Pahari speakers are Hindi speakers, who have learned only Hindi as language with conjunct consonants, it would be better to keep this as an additional option that has to be manually enabled.

**Comment by virtualvinodh** [comment]
This has been done.
