### ISSUE TITLE
Improper rendering blogspot websites.

### ISSUE THREAD

**Issue by nik9hil** [virtualvinodh/aksharamukha#66]
Blogspot websites are not being properly rendered in the website converter.

![image](https://user-images.githubusercontent.com/32241740/85289370-f83bc100-b4b4-11ea-846c-2a3915afd41e.png)

The issue seems script independent. It is to be noted that text copied from the same website are properly converted in the converter.

**Comment by virtualvinodh** [comment]
Yeah. This is a known issue. I have to see what blogpost is doing differently in terms of encoding the text. It seems a bit weird. 

I'll have a look into it when I have time.

V
