### ISSUE TITLE
Contextual ன appearing word-initially in Tamil (Extended)

### ISSUE THREAD

**Issue by kubhasena** [virtualvinodh/aksharamukha#67]
When transliterating into Tamil (Extended) with the contextual ன option enabled, it converts ந to ன whenever it is followed by another consonant, even word-initially. For example न्यास is transliterated as ன்யாஸ. This seems jarring to read as ன is never used word-initially in Tamil.

**Comment by virtualvinodh** [comment]
This has been fixed.

V
