### ISSUE TITLE
convert from Image feature not showing

### ISSUE THREAD

**Issue by Nj-KiiNG-108** [virtualvinodh/aksharamukha#69]
I cannot see the upload image icon below the input text box in the converter mode. Has this feature been removed? 
![image](https://user-images.githubusercontent.com/68019393/86934368-852c7e80-c133-11ea-951b-9a874456049b.png)
![image](https://user-images.githubusercontent.com/68019393/86934514-ae4d0f00-c133-11ea-8d30-edee0dc3825a.png)

**Comment by Raj-Kishore-Rout** [comment]
Please Restore this feature. This was of immense help.

**Comment by virtualvinodh** [comment]
I will add this soon.

**Comment by Nj-KiiNG-108** [comment]
Thank you Virtualvinodh ji, we look forward to this!
