### ISSUE TITLE
Grantha font not copy and paste properly in word

### ISSUE THREAD

**Issue by sendusree** [virtualvinodh/aksharamukha#70]
i have typed a slokam and agama mantras in aksharamukha, the grantha letters are showing properly in the website , while i try to copy and paste to MSword, some letters are changed, ex: if i type namaste its show like this....
![text (2)](https://user-images.githubusercontent.com/68243164/87332940-0633ad80-c55a-11ea-9ea1-7e0fb754d983.png)
while paste in to word its shows like this....
![namaste](https://user-images.githubusercontent.com/68243164/87333204-6a567180-c55a-11ea-9820-55621fe36606.jpg)
please tell me the solution for this, we r running an vedaagama patasalai.

**Comment by punchcutter** [comment]
This works for me in the latest Word (Office 365 download (version 2006 build 13001.20266)) on Windows 10. If you have an older version of Word it probably won't work to display Grantha correctly. Which version are you using?

**Comment by sendusree** [comment]
I am using word 2010

**Comment by punchcutter** [comment]
Unfortunately, Word 2010 won't work correctly for Grantha because the shaping required was only added starting in 2016, but really didn't get working until around 2018-2019. The best thing to do here is use the most recent version of Word.

**Comment by virtualvinodh** [comment]
The font is also not Noto Sans/Serif Grantha. MS Word 2010 is actually picking up e-Grantamil as the default font for Grantha.  I'd suggest you download Noto Sans Grantha from here:

https://cdn.jsdelivr.net/gh/virtualvinodh/aksharamukha/aksharamukha-front/src/statics/NotoSansGrantha-RegularZach.otf

And also updated your MS Office version as suggested by Zachary.

You can also try Libre Office to typeset documents. It is free to download and use.

https://www.libreoffice.org/download/download/

V

**Comment by sendusree** [comment]
thank you so much, its working for me

**Comment by virtualvinodh** [comment]
Could you let us know how you fixed the issue?
