### ISSUE TITLE
Grantha Wrong Font Issue

### ISSUE THREAD

**Issue by Krishnarmm** [virtualvinodh/aksharamukha#71]
Koti Namaskarams For This Beautiful Thing You Done For Us.. No One Is Here Ready To Do This In The World I Think.. Grantha Is Very Less Known Language. Amazing Work.
Actually The Font "Tra" is Wrong.. Can You Plz Correct That..!?
Will Attach The Image What I'm Actually Saying.. Thank You So Much. 🙏
![aksharamukha_2020614111657](https://user-images.githubusercontent.com/68266301/87389294-1f714400-c5c4-11ea-81cc-c1b3ab041149.png) 
![IMG-20200714-WA0012](https://user-images.githubusercontent.com/68266301/87389414-55162d00-c5c4-11ea-8946-2a8e43c47d79.jpg)

**Comment by virtualvinodh** [comment]
The form used in the font is just an alternate variant of  /tra/. Both are valid. 

If you'd like to the second variant, you can get it by typing t[]ra, t[]ro etc.

V

**Comment by Krishnarmm** [comment]
Thank You So Much.. If I Convert From Sanskrit.. What Can I Do..?? "त्र" Is
Not Good.. What I Said Earlier That Akshara Coming..

**Comment by virtualvinodh** [comment]
They are pretty much the same. 

If you'd like to use the form you want to use, you have to do it manually. Unfortunately, I cannot add it as an option here.
