### ISSUE TITLE
OM in Tamil

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#73]
Hello Vinod,

There used to be a switch option to change ॐ to ஓம் instead of ௐ in Tamizh. 

Please re-introduce this option. 

Like ओम् or ओं transcribes to ஓம். 

Thanks 
Seshadri

**Comment by virtualvinodh** [comment]
Is it because of readability, you want that back?

**Comment by nsesha92** [comment]
yes please

--------------
Warm regards
Seshadri

**Comment by virtualvinodh** [comment]
done

**Comment by nsesha92** [comment]
Thanks a ton, much appreciated.
--------------
Warm regards
Seshadri
