### ISSUE TITLE
Implement Malayalam reph consonant doubling rules using a virama for Sanskrit words containing a reph

### ISSUE THREAD

**Issue by the-divine-dev** [virtualvinodh/aksharamukha#75]
Vinodh and company, thank you for your indispensable service of computerizing and preserving traditional orthography of Indic scripts.

**Feature request:**

- Include post_option to add consonant doubling rules after a reph when transliterating to Malayalam from a script representing Sanskrit (Devanagari, HK, IAST, etc).

- Include pre_option to remove consonant doubling rules after a reph when transliterating from Malayalam to another script representing Sanskrit (Devanagari, HK, IAST, etc.)

**More details:**

Package currently does not implement a common convention used in Malayalam when writing Sanskrit words containing a reph.

For example, सर्वं is written as സൎവ്വം not സൎവം typically. धर्मं is written ധൎമ്മം not ധൎമം in practice. वर्यः is written വൎയ്യഃ. An extra consonant + virama was introduced after the reph in each case.

For words in which the consonant is already doubled by means of a virama in Sanskrit, nothing changes, like in अमूर्त्तरयः is written exactly the same way അമൂൎത്തരയഃ.

If the letter following the reph already has a virama in Sanskrit, consonant doubling isn't applied. And if the letter preceding the reph already has a virama in Sanskrit, then consonant doubling isn't applied, such as सध्र्यक् to സധ്ര്യക് ... Notice the र् (ര്) sound is not represented as a reph in this case due to this very rule.

However, there are slightly more complicated rules, like अर्थं is written അൎത്ഥം (notice, rather than strictly doubling the consonant, ത് was added after the reph) rather than അൎഥം.

There are letters for which this does not apply at all, such as if the reph comes before a vowel, or letters like "ഷ", like in राजर्षिः which is written as expected രാജൎഷിഃ. Another example is for "ഭ", where विभुर्भगवान् is written വിഭുൎഭഗവാൻ as expected. Doubling also doesn't apply to ഹ as in 
ബൎഹി.

There are more such rules for consonant doubling after a reph than stated here. I'm happy to send PDFs of old publications so you can see more of these rules applied in practice.

Joined consonants are one of the more complex aspects of Malayalam script, but also a beautiful aspect. No software library has been able to display old font Malayalam joined letters and convert to Malayalam like Aksharamukha. If this could be added without breaking currently working  consonant ligatures, that would be great! I wouldn't want currently correct rendering to be affected by adding this rule.

I am also only now consciously keeping track of when this rule occurs and when it doesn't. I'll update this request as I notice more. It will take research to apply all instances of this convention correctly.

**Comment by virtualvinodh** [comment]
Thanks for the brilliant suggestion. I always wondered if I should implement this consonant doubling. 

Is it possible for you to provide rules for all the consonants?

r + k > rkka
etc. 

There shouldn't be a problem to implement this feature.

V

**Comment by the-divine-dev** [comment]
Hi Vinodh,
Thanks so much! I have a large text corpus and will search it for the different Malayalam reph consonant doubling rules (a partly manual process). I will post a consolidated list of the rules for you within the next several days.

Would this update be included across all aksharamukha tools (PyPi package, online tool, etc.)?

**Comment by virtualvinodh** [comment]
Yup.  I have a single python backend. So everything will be updated at the same time.

**Comment by the-divine-dev** [comment]
I am making good progress collecting the rules... About 10 more days and I'll post them here. Haven't forgotten :)

**Comment by virtualvinodh** [comment]
Great. Looking forward to it 👍

**Comment by lianghai** [comment]
So is the rule preferred by Malayalam gonna be summarized as something like “a post-repha (in its narrow sense, an onset-initial [r]) consonant is geminated if it is a voiceless plosive or sonorant except r and h,” (ie, not affecting voiced plosives, fricatives, r, and h)?

**Comment by virtualvinodh** [comment]
@the-divine-dev I was wondering if there are any updates?

I am planning to work on a bunch of tweaks in the coming weeks. I thought I'll include this as well.

V

**Comment by virtualvinodh** [comment]
@the-divine-dev Just wanted to know, how you're getting along 👍 

V

**Comment by cibu** [comment]
Let me try to list the rules. That is, if the akshara is of the form
<dot-reph, consonant> or <dot-reph, consonant, vowel-sign>, then the consonant gets substituted as follows:

1. ക → ക്ക
2. ഗ → ഗ്ഗ
3. ച → ച്ച
4. ഛ → ച്ഛ
5. ജ → ജ്ജ
6. ട → ട്ട
7. ഡ → ഡ്ഡ
8. ഢ → ഡ്ഢ
9. ണ → ണ്ണ
10. ത → ത്ത
11. ഥ → ത്ഥ
12. ദ → ദ്ദ
13. ധ → ദ്ധ
14. ന → ന്ന
15. പ → പ്പ
16. ബ → ബ്ബ
17. മ → മ്മ
18. യ → യ്യ
19. വ → വ്വ
20. ശ → ശ്ശ
21. സ → സ്സ
22. ള → ള്ള

**Comment by virtualvinodh** [comment]
@cibu  Thanks a lot. That's very helpful!

V

**Comment by virtualvinodh** [comment]
Done

**Comment by vivekbabu** [comment]
Hi @virtualvinodh,

I can see that this feature is now available online. 

But when I run it locally using docker compose i see that 'Double consonants after reph ധർമ → ധർമ്മ' option is not available.

Is it that the code change is not committed to master and also the latest docker image not updated accordingly

Can you please advice

Thanks in Advance

Vivek

**Comment by virtualvinodh** [comment]
@vivekbabu I haven't updated the docker image yet.

I will let you know once I update the docker image.

V
