### ISSUE TITLE
number transliteration

### ISSUE THREAD

**Issue by vvasuki** [virtualvinodh/aksharamukha#78]
Surprised that I never noticed it below.

912 translated to devanAgarI ought to yield ९१२ on the website. It does not.

**Comment by virtualvinodh** [comment]
@vvasuki Do you mean Website transliteration?

If that's the case, it is intentional. 

Since, I convert the HTML source per se, it prevents <h2></h2> being converted to <h२></h२>

V

**Comment by vvasuki** [comment]
Ah - foolish of me to not have included a screenshot. Now I don't recall where I faced this problem. Closing for now.
