### ISSUE TITLE
Issue with multiple checkbox selection in the output in certain cases

### ISSUE THREAD

**Issue by sridatta1** [virtualvinodh/aksharamukha#79]
In the output, where multiple unrelated options can be selected.
Like, Archaic II, repha options in Malayalam
![image](https://user-images.githubusercontent.com/23263723/98463341-94eec900-21e0-11eb-9a77-1207ebeae2e9.png)

But for selecting from multiple variants/ styles/ fonts, only one checkbox needs to be selected, currently one can select all the options.
1. Selecting Landza, Wartu styles. 
![image](https://user-images.githubusercontent.com/23263723/98464049-20b72400-21e6-11eb-8013-5b1bfd14e226.png)
2. Variant forms of I in Siddham
![image](https://user-images.githubusercontent.com/23263723/98464091-683db000-21e6-11eb-94c2-f2b757c3a35a.png)
3. Font selection in Siddham
![image](https://user-images.githubusercontent.com/23263723/98464117-96bb8b00-21e6-11eb-8268-cac89c082d26.png)
4. Selecting between e-Grantamil font encoding and Noto Serif Grantha font
![image](https://user-images.githubusercontent.com/23263723/98464228-7809c400-21e7-11eb-84d2-e8f6e9a22328.png)
And similarly other cases.
In these cases if I select the 2nd option while the 1st option is also selected, the 1st option needs be unchecked automatically.

**Comment by virtualvinodh** [comment]
fixed
