### ISSUE TITLE
Roman ITRANS coding discrepancy

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#82]
ITRANS to Dev conversion for few are not matching ITRANS coding:

input	ak	ITO
Ja	        **Jअ**	ज़
J | z	       **J | ज़्**	ज़्‌ । ज़्‌

J=z mapped to ज़्‌

For zh & z-h, ak's output differs when reversed:

input    ak
zh	    ऴ्
z-h	    ज़्-ह्
	
ऴ्	  zh
ज़्-ह्	  z-h
ज़्ह्	  zh

Hope you will take care of this, thanks

**Comment by virtualvinodh** [comment]
Would you mind providing a link to the updated ITRANS mapping?

**Comment by nsesha92** [comment]
The new one is at https://www.aczoom.com/itrans/online/

But please *don't map* ee = ஈ and ṅ ( n with nukta) to nga.

On the e / E, u / U, I don't like this #roman AND #roman-south -> why
this *North
/ South* DIVIDE?

Should go with ISO 15919 recommendations:
https://en.wikipedia.org/wiki/ISO_15919 :

- To distinguish between long and short 'e' in Dravidian languages, 'e' now
represents ऎ / ॆ (short).
- To distinguish between long and short 'o' in Dravidian languages, 'o' now
represents ऒ / ॊ (short).

My take, new itransonline can be made ISO 15919 compliant, while keeping
the old version still available at the old site for reference/usage of old
itx docs. Not sure how to convince and effect this change. itranslator99
follows old coding.

Thanks to you, you have introduced the e/E,o/O switch.

*R for Tamil rrra and L for Tamil llla, different from old version, *keep
them.

On the Candra, bit of a confusion. While in the old version ( and in
itranslator99/2003)  .c is for candra, in the new version it is missing.

What to map for .c ?
x1CF4 ?
Is it a combining sign?

Can .c =  x1CF4

and

a.c = ॲ (x0972)    candra A  ( instead of a.e )
e.c = ऍ (0x090D)  candra E  ( instead of a.c )
A.c = ऑ (0x911)   candra O

The old one (pre-Unicode days?) is at
https://www.aczoom.com/itrans/#itransencoding

And also क़  can be ka.c,    ग़ = ga.c and so on.
--------------
Warm regards
Seshadri

**Comment by virtualvinodh** [comment]
I have fixed the mappings for J and zh.

I don't think this is the place to improve ITRANS. There are lots of existing documents that are already in Itrans.

And anyways, with Unicode. There isn't any need to keep using Itrans.

V

**Comment by nsesha92** [comment]
Thanks.

I know, it is not about changing or improving ITRANS, that is left to
ITRANs/Avinash Chopde.

Since ITRANs is one of the Input/Output options in aksharamukha, ak should
be consistent with ITRANS ( just like IAST ...)

--------------
Warm regards
Seshadri

**Comment by the-solipsist** [comment]
I thought I'd just add that ISO15919 isn't immune to ITRANS's "roman"/"roman-south" divide either.  Many texts in ISO15919 opt for "Option 9.1", which allows for the short-e/long-e or short-o/long-o distinction to be optionally avoided.

Even the DHARMA project, a large-scale project involving much transliteration of Indic scripts past and present, [opts for this](https://hal.archives-ouvertes.fr/halshs-02272407v3/document):

> ## 3.2. Long and Short e and o
> * when transliterating a language that does not make a distinction between long and short e and o, use these Latin characters without a macron
>   * this corresponds to Option 9.1 of the ISO15919 standard, applicable to languages that do not make a distinction between the phonemes e/ē and o/ō
> * however, for Dravidian languages that distinguish long and short e and o, you have the option to record that distinction even if it is not present in the script you are working with
>   * in this case, transcribe long vowels as ē/ō even in strict transliteration
>   * these characters will be treated as shorthand, subsequently to be automatically expanded with XML markup signifying that e or o was in fact inscribed, but the spelling has been normalised by the editor
>     * that is to say, the palaeographically primary generic vowel marker, e.g. that in ெக ke, ெகா ko, may represent either a short or a long vowel; when it represents a long vowel, this will be shown as an editorial normalisation, e.g. to ேக kē, ேகா kō
>   * should your inscription (or manuscript) explicitly distinguish between short and long e/o, please contact us to devise a solution for handling this

**Comment by nsesha92** [comment]
Thanks for sharing about DHARMA project. 

I also checked scanscript, its ITRANS mapping is old and not updated.
Also, there is no option for short e & o for even Tamizh.

I have given my suggestions to ITRANS/Avinash:

https://github.com/avinash311/itrans/issues

and leave it at that.

**Comment by nsesha92** [comment]
My suggestion is implemented.

https://github.com/avinash311/itrans/issues/4
