### ISSUE TITLE
Request for retaining ற clusters in Tamil Transcription

### ISSUE THREAD

**Issue by kubhasena** [virtualvinodh/aksharamukha#84]
Currently when using the Transcribe Tamil pre-option ற்ற gets transcribed as ṭra and ன்ற as ṇḍra. Is it possible to add a pre-option that would retain these as ṟṟa and ṉṟa instead?

Thanks in advance!!

**Comment by virtualvinodh** [comment]
What would be the use-case for this? I mean it is a transcription after all.

**Comment by kubhasena** [comment]
When transliterating texts from Tamil, currently both ட்ர and ற்ற will collapse onto the same transcription, namely ṭra. So it becomes difficult to tell them apart in pronunciation when reading.

Whereas with this pre-option, the two clusters will remain distinct after transliteration as well.

**Comment by virtualvinodh** [comment]
Tamil has already too many options. We are transcribing Tamil anyway, it makes sense for some sequences to get transcribed the same way.

**Comment by kubhasena** [comment]
Sir, there's only two pre-options for Tamil as of now... Perhaps, this can be implemented as a functionality of the "Preserve Source" option? It seems like that would be a logical place for it.

**Comment by thevaram-class** [comment]
In Tamil language, the combination - ட்ர - does not occur. Only ற்ற can occur. 
Only some English words - such as Central, Petrol, etc. are being written in Tamil as சென்ட்ரல், பெட்ரோல், etc.
Sanskrit has ட்ர combination - राष्ट्र - ராஷ்ட்ர - etc. But Sanskrit words are typically written in Tamil using Tamil convention - such as ராஷ்டிரம், மகராஷ்டிரம் / மஹராஷ்டிரம், etc.

**Comment by kubhasena** [comment]
I am aware, sir. I was hoping to use it to transliterate certain texts that had mixed usage of the tatsamas (some words with ட்ர and some with ட்டிர). But it's not too bad without it. As there were only a few instances of ட்ர, it wasn't too difficult to simply replace all ट्र with ऱ्ऱ and manually correct the few actual ட்ரs.
