### ISSUE TITLE
Request for support of Kashmiri vowels ॶ, ॷ, ॳ, ॴ, and ॵ

### ISSUE THREAD

**Issue by vbharadvaja** [virtualvinodh/aksharamukha#85]
ॶ (ॖ) is variously transliterated into Roman as û, ü, or ɨ, although ü is the most common. ॷ (ॗ) is the same with a macron added.

ॶ also corresponds in pronunciation with the kuttriyalukaram/samvritokaram in Tamil and Malayalam. In Malayalam, this is often represented with a chandrakkala combined with an u-matra (e.g. कॖ == കു്‌). This can be extended to cover ॷ as well (कॗ == കൂ്‌).

For other scripts, these sounds can be represented as their symbols for u/ū + some modifier, either the virama or *, ^, #, etc.

ॳ (ऺ) is generally transliterated as ö or ə and ॴ (ऻ) similarly with a macron. It can be transliterated in other scripts by adding ^ or * to their respective symbols for a/ā.

And finally ॵ (ॏ) is transliterated as ọ is Roman. In other scripts, it could possibly be represented as au with some marking (*, ^, etc.).

Thanks so much for making this software! It has been immensely helpful to me when transliterating texts and even more so for learning new scripts.

**Comment by virtualvinodh** [comment]
Thanks for the issue.  You pretty much provided all the information needed.

I will add the support when I am updating the tool.

V

**Comment by vbharadvaja** [comment]
Thank you very much, sir!! 🙏🙏

**Comment by virtualvinodh** [comment]
fixed.
