### ISSUE TITLE
Replace Shan Font

### ISSUE THREAD

**Issue by virtualvinodh** [virtualvinodh/aksharamukha#89]
https://github.com/googlefonts/noto-fonts/issues/1811

**Comment by SZTSIIT** [comment]
@virtualvinodh What was the replacement? I don't see any changes on the font.

**Comment by virtualvinodh** [comment]
@SZTSIIT I changed it to GreatHorKham_Taunggyi. I saw that you suggested it in the Noto fonts project.

**Comment by SZTSIIT** [comment]
@virtualvinodh  Thank You. I will take alook into your project.
