### ISSUE TITLE
Velthuis to Devanāgarī

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#9]
Can't type or transliterate to these characters.
a a.h k.h m.h b.h >अ अः क्ः म्ः ब्ः

You may change a.h to aH to get अः
Then k.h, m.h, b.h will get transliterated to क् , म् , ब्
Please correct.

**Comment by virtualvinodh** [comment]
I just checked. It is working as expected.  I am not sure what trouble you're having.

**Comment by virtualvinodh** [comment]
Velthuis is a standard format and it just can't be changed

If you would like to stop conjunct formation, you need to add ZWNJ after the virama. Currently, it is not possible. But I will update this thread when I add such option.

V

**Comment by geethub** [comment]
Thanks.
Here are Google input keystrokes.
अ्‌ /a.h  अ/a, aa/आ, इ/i, ई/ii, उ/u, ऊ/uu, ऍ/e.c, ए/e,ऐ /ai,ऑ/o.c, ओ/o, औ/au, अं/am/an  अः/aH, ऋ/R, ॠ/RR
