### ISSUE TITLE
avagraha

### ISSUE THREAD

**Issue by nsesha92** [virtualvinodh/aksharamukha#90]
Hello,

avagraha used to coded for all scripts, but now missing from tamil and grantha

please add .a = avagraha for both

thanks

**Comment by virtualvinodh** [comment]
It should work. What scheme are you using?

V

**Comment by nsesha92** [comment]
ITRANS:

.a =  ऽ

.a =   (அ)

ITRANS uses Grantha  U+1133D for Tamil and it works.

--------------
Warm regards
Seshadri

**Comment by virtualvinodh** [comment]
Nah. I don't think many people are familiar with the Grantha Avagraha anyway. I would retain (a). 

If someone wants more Grantha characters, they can always use Tamil extended.

V
