### ISSUE TITLE
Ligature free Devanagari / Indic scripts output 

### ISSUE THREAD

**Issue by geethub** [virtualvinodh/aksharamukha#93]
**Is there a way to get **ligature free** output for educational purpose?**

**स्वतंत्रता, उद्देश्य ,राष्ट्रीय, अभिव्यक्ति, शब्द, मुश्किल >>स्‌वतंत्‌रता, उद्‌देश्‌य ,राष्‌ट्‌रीय, अभिव्‌यक्‌ति, शब्‌द, मुश्‌किल**

**Comment by geethub** [comment]
**Needed improvement in Readable output**
**ष,ण,ञ > s'a,n'a,n'ya**

**Comment by virtualvinodh** [comment]
Not currently. I don't see the need to add this as of now. There aren't many use-cases for this.

**Comment by geethub** [comment]
Mr.Rajan,
If not possible, please write for me a *Firefox regular Expression*
for *ligature
free* Devanagari and Gujarati script so I can try.
स्वतंत्रता, उद्देश्य ,राष्ट्रीय, अभिव्यक्ति, शब्द, मुश्किल >>स्‌वतंत्‌रता,
उद्‌देश्‌य ,राष्‌ट्‌रीय, अभिव्‌यक्‌ति, शब्‌द, मुश्‌किल
સ્વતંત્રતા, ઉદ્દેશ્ય ,રાષ્ટ્રીય, અભિવ્યક્તિ, શબ્દ, મુશ્કિલ >>સ્વતંત્રતા,
ઉદ્દેશ્ય ,રાષ્ટ્રીય, અભિવ્યક્તિ, શબ્દ, મુશ્કિલ
Thanks,
ken
