### ISSUE TITLE
Batch convert docx file defect: converts XML tags which results in invalid xml

### ISSUE THREAD

**Issue by jups23** [virtualvinodh/aksharamukha#97]
Tested with Roman IAST input and output Devanagari as well as Bengali.

The problem seems to be that aksharamukha converts also the text _inside_ the xml tags and not only the text in the text nodes. 

Therefore, document.xml starts with `<xम्ल वेर्सिोन्="१।०”` instead of `<xml version="1.0"`

See the input and output documents attached. 

Settings: 
<img width="833" alt="Screen Shot 2021-02-21 at 16 36 47" src="https://user-images.githubusercontent.com/217980/108623083-063a4b00-7463-11eb-98c0-39f0d6cc20d1.png">

Input file: [test1.docx](https://github.com/virtualvinodh/aksharamukha/files/6017573/test1.docx)

Output Devanagari: [IAST_Devanagari_test.docx](https://github.com/virtualvinodh/aksharamukha/files/6017572/IAST_Devanagari_test.docx)

Output Devanagari: [IAST_Bengali_test1.docx](https://github.com/virtualvinodh/aksharamukha/files/6017570/IAST_Bengali_test1.docx)

**Comment by virtualvinodh** [comment]
I am closing this. I am keeping the other issue open to keep track of this.
