### ISSUE TITLE
docx conversion: Convert also footnotes, endnotes, headers, footers, and comments

### ISSUE THREAD

**Issue by willi-mueller** [virtualvinodh/aksharamukha#98]
For complete conversion of scripts in a docx file the following xml files need to be processed, alongside with word/document.xml:

1. word/footnotes.xml
2. word/endnotes.xml
3. word/comments.xml
4. word/footer1.xml
5.  word/footer2.xml
6. word/header1.xml
7. word/header2.xml

Please note that all these files need to be processed as XML, meaning that only the content enclosed within the tags <ns0:t></ns0:t> are to be converted to the target script. Not the tags, such as `ns0:t` itself. See #97.

**Comment by yakcz** [comment]
Would you mind to advise us, dummies, as to how does one obtain the above mentioned .xml files from the source .docx ?

**Comment by virtualvinodh** [comment]
This is finally done and deployed!! 

Thanks a lot!

**Comment by willi-mueller** [comment]
This is so wonderful! I just tried it and shared it with my community!
Thank you very much @virtualvinodh !
